substitutions:
  _TURBO_TOKEN: ""
  _TURBO_TEAM_ID: ""
  _SERVICE_NAME: "parent-portal"

steps:
  # Step 1: Enable Corepack and install dependencies
  - name: node:24-alpine
    id: Install & Build
    entrypoint: sh
    env:
      - TURBO_TOKEN=${_TURBO_TOKEN}
      - TURBO_TEAM_ID=${_TURBO_TEAM_ID}
    args:
      - -c
      - |
        corepack enable
        yarn install --immutable
        yarn build

  # Step 2: Build Docker image
  - name: gcr.io/cloud-builders/docker
    id: Docker Build
    args:
      [
        "build",
        "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}",
        "."
      ]