name: nccl-parents-local

services:
  db:
    image: postgres:17
    container_name: db-local
    restart: unless-stopped
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: nccl-parents-local
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 6543
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
