name: nccl-parents-e2e
services:
  db:
    image: postgres:17
    ports:
      - "11002:5432"
    env_file:
      - ./.env
      - ./.env.spec
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
      args:
        NODE_ENV: test
    ports:
      - "11001:8080"
    env_file:
      - ./.env
      - ./.env.spec
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: packages/app/Dockerfile
      args:
        NODE_ENV: test
    ports:
      - "11000:8080"
    env_file:
      - ./.env
      - ./.env.spec

    depends_on:
      - api
