// -------------------------------------------------------
//  ⚠️ WARNING: AUTO-GENERATED FILE
//  This file is generated by buttery-tokens and should not be edited.
//  Any edits that are made will be overwritten the next time the
//  buttery-tokens CLI is run.
// -------------------------------------------------------
export type CustomTokens =
  | "navbar--height-mobile"
  | "navbar--width-desktop"
  | "header--height-desktop"
  | "page--gutter-desktop"
  | "page--gutter-mobile";
export type MakeCustom = (tokenName: CustomTokens) => string | number;

/**
 * ## `makeCustom`
 * Enables to references custom tokens that don't fit within the bounds of the static configuration points. This is good for things like navigational headers, footers, or any other heights, 1-off colors, etc... that need to be shared across all parts of the application
 */
export const makeCustom: MakeCustom = (value) => {
  return `var(--nccl-custom-${value})`;
};
