// -------------------------------------------------------
//  ⚠️ WARNING: AUTO-GENERATED FILE
//  This file is generated by buttery-tokens and should not be edited.
//  Any edits that are made will be overwritten the next time the
//  buttery-tokens CLI is run.
// -------------------------------------------------------
export type MakeFontBaseSize = (token: number) => string;

/**
 * ## `makeFontBaseSize`
 * Returns the token used to set the base font size of the document body.
 */
export const makeFontBaseSize: MakeFontBaseSize = (value) => {
  return `var(--nccl-font-base-${value})`;
};
