// -------------------------------------------------------
//  ⚠️ WARNING: AUTO-GENERATED FILE
//  This file is generated by buttery-tokens and should not be edited.
//  Any edits that are made will be overwritten the next time the
//  buttery-tokens CLI is run.
// -------------------------------------------------------
export type MakeReset = (
  element: "ul" | "button" | "body" | "anchor" | "input",
) => string;

const matchGuard = (_: never): never => {
  throw new Error(`Forgot to include an ${_} in the switch statement`);
};

export const makeReset: MakeReset = (element) => {
  switch (element) {
    case "ul":
      return `
          margin: 0;
          padding: 0;

          li {
            margin: 0;
            padding: 0;
            list-style-type: none;
          }
        `;

    case "button":
      return `
          margin: 0;
          padding: 0;
          border: none;
          background: none;
        `;

    case "body":
      return `
          margin: 0;
          padding: 0;
        `;

    case "anchor":
      return `
          text-decoration: none;
          color: inherit;

          &:visited {
            color: inherit;
          }
        `;

    case "input":
      return `
          margin: 0;
          padding: 0;
          border: none;
          background: none;
          font: inherit;
          color: inherit;
          appearance: none;
          outline: none;
          box-sizing: border-box;
          width: inherit;

          &[type="number"]::-webkit-inner-spin-button,
          &[type="number"]::-webkit-outer-spin-button {
            appearance: none;
            margin: 0;
          }

          // range
          &[type="range"]::-ms-track {
            background: transparent; /* Transparent since MS uses a pseudo track */
            border-color: transparent;
            color: transparent;
          },
          &[type="range"]::-webkit-slider-thumb {
            appearance: none;
            -webkit-appearance: none; /* Removes default styling */
          }
          &[type="range"]:focus {
            outline: none;
          }
        `;

    default:
      return matchGuard(element);
  }
};
