// -------------------------------------------------------
//  ⚠️ WARNING: AUTO-GENERATED FILE
//  This file is generated by buttery-tokens and should not be edited.
//  Any edits that are made will be overwritten the next time the
//  buttery-tokens CLI is run.
// -------------------------------------------------------
/**
 * ## `makePx`
 * A utility that concatenates 'px' onto the end of the provided value
 */
export const makePx = (val: number) => `${val}px`;
