name: "Setup & Install"
description: "Set's up node and prepares the repo for CI & CD"
author: "Drew DeCarme (drew@greenflash.digital)"

runs:
  using: "composite"
  steps:

    - name: Enable corepack # Ensures the correct version of yarn is used
      shell: bash 
      run: corepack enable

    - name: Create .env file
      shell: bash
      run: |
        cat > .env <<'EOF'
          
        EOF

    - name: Create .env file
      shell: bash
      run: |
        touch .env
        echo TURBO_TOKEN=${{ secrets.TURBO_TOKEN }} >> .env
        echo TURBO_TEAM_ID=${{ secrets.TURBO_TEAM_ID }} >> .env
        echo NODE_ENV=production >> .env
        echo NCCL_ENVIRONMENT=${{ vars.NCCL_ENVIRONMENT }} >> .env
        echo NCCL_APP_URL=${{ vars.NCCL_APP_URL }} >> .env
        echo NCCL_API_URL=${{ vars.NCCL_API_URL }} >> .env
        echo GCP_CLOUD_STORAGE_BUCKET=${{ secrets.GCP_CLOUD_STORAGE_BUCKET }} >> .env
        echo BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }} >> .env
        echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
        echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
        echo SUPER_USER_PASSWORD=${{ secrets.SUPER_USER_PASSWORD }} >> .env
        echo SUPER_USER_EMAIL=${{ secrets.SUPER_USER_EMAIL }} >> .env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env

    - name: Set Up node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        node-version-file: .nvmrc
        cache: "yarn"

    - name: Install dependencies
      shell: bash 
      run: yarn install --immutable

    - name: Build
      shell: bash 
      run: yarn build

    - name: Install production dependencies
      shell: bash 
      run: yarn workspaces focus --production --all