name: "Setup & Install"
description: "Set's up node and prepares the repo for CI & CD"
author: "Drew DeCarme (drew@greenflash.digital)"

runs:
  using: "composite"
  steps:

    - name: Enable corepack # Ensures the correct version of yarn is used
      shell: bash 
      run: corepack enable

    - name: Set Up node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: "yarn"

    - name: Install dependencies
      shell: bash 
      run: yarn install --immutable

    - name: Build
      shell: bash 
      run: yarn build

    - name: Install production dependencies
      shell: bash 
      run: yarn workspaces focus --production --all