
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `SuggestionVote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SuggestionVote
 * 
 */
export type SuggestionVoteModel = runtime.Types.Result.DefaultSelection<Prisma.$SuggestionVotePayload>

export type AggregateSuggestionVote = {
  _count: SuggestionVoteCountAggregateOutputType | null
  _min: SuggestionVoteMinAggregateOutputType | null
  _max: SuggestionVoteMaxAggregateOutputType | null
}

export type SuggestionVoteMinAggregateOutputType = {
  id: string | null
  type: $Enums.SuggestionVoteType | null
  createdAt: Date | null
  updatedAt: Date | null
  createdById: string | null
  suggestionId: string | null
}

export type SuggestionVoteMaxAggregateOutputType = {
  id: string | null
  type: $Enums.SuggestionVoteType | null
  createdAt: Date | null
  updatedAt: Date | null
  createdById: string | null
  suggestionId: string | null
}

export type SuggestionVoteCountAggregateOutputType = {
  id: number
  type: number
  createdAt: number
  updatedAt: number
  createdById: number
  suggestionId: number
  _all: number
}


export type SuggestionVoteMinAggregateInputType = {
  id?: true
  type?: true
  createdAt?: true
  updatedAt?: true
  createdById?: true
  suggestionId?: true
}

export type SuggestionVoteMaxAggregateInputType = {
  id?: true
  type?: true
  createdAt?: true
  updatedAt?: true
  createdById?: true
  suggestionId?: true
}

export type SuggestionVoteCountAggregateInputType = {
  id?: true
  type?: true
  createdAt?: true
  updatedAt?: true
  createdById?: true
  suggestionId?: true
  _all?: true
}

export type SuggestionVoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SuggestionVote to aggregate.
   */
  where?: Prisma.SuggestionVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SuggestionVotes to fetch.
   */
  orderBy?: Prisma.SuggestionVoteOrderByWithRelationInput | Prisma.SuggestionVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SuggestionVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SuggestionVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SuggestionVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SuggestionVotes
  **/
  _count?: true | SuggestionVoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SuggestionVoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SuggestionVoteMaxAggregateInputType
}

export type GetSuggestionVoteAggregateType<T extends SuggestionVoteAggregateArgs> = {
      [P in keyof T & keyof AggregateSuggestionVote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSuggestionVote[P]>
    : Prisma.GetScalarType<T[P], AggregateSuggestionVote[P]>
}




export type SuggestionVoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SuggestionVoteWhereInput
  orderBy?: Prisma.SuggestionVoteOrderByWithAggregationInput | Prisma.SuggestionVoteOrderByWithAggregationInput[]
  by: Prisma.SuggestionVoteScalarFieldEnum[] | Prisma.SuggestionVoteScalarFieldEnum
  having?: Prisma.SuggestionVoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SuggestionVoteCountAggregateInputType | true
  _min?: SuggestionVoteMinAggregateInputType
  _max?: SuggestionVoteMaxAggregateInputType
}

export type SuggestionVoteGroupByOutputType = {
  id: string
  type: $Enums.SuggestionVoteType
  createdAt: Date
  updatedAt: Date
  createdById: string
  suggestionId: string
  _count: SuggestionVoteCountAggregateOutputType | null
  _min: SuggestionVoteMinAggregateOutputType | null
  _max: SuggestionVoteMaxAggregateOutputType | null
}

type GetSuggestionVoteGroupByPayload<T extends SuggestionVoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SuggestionVoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SuggestionVoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SuggestionVoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SuggestionVoteGroupByOutputType[P]>
      }
    >
  > 



export type SuggestionVoteWhereInput = {
  AND?: Prisma.SuggestionVoteWhereInput | Prisma.SuggestionVoteWhereInput[]
  OR?: Prisma.SuggestionVoteWhereInput[]
  NOT?: Prisma.SuggestionVoteWhereInput | Prisma.SuggestionVoteWhereInput[]
  id?: Prisma.StringFilter<"SuggestionVote"> | string
  type?: Prisma.EnumSuggestionVoteTypeFilter<"SuggestionVote"> | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFilter<"SuggestionVote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SuggestionVote"> | Date | string
  createdById?: Prisma.StringFilter<"SuggestionVote"> | string
  suggestionId?: Prisma.StringFilter<"SuggestionVote"> | string
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  suggestion?: Prisma.XOR<Prisma.SuggestionScalarRelationFilter, Prisma.SuggestionWhereInput>
}

export type SuggestionVoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
  createdBy?: Prisma.UserOrderByWithRelationInput
  suggestion?: Prisma.SuggestionOrderByWithRelationInput
  _relevance?: Prisma.SuggestionVoteOrderByRelevanceInput
}

export type SuggestionVoteWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  createdById_suggestionId?: Prisma.SuggestionVoteCreatedByIdSuggestionIdCompoundUniqueInput
  AND?: Prisma.SuggestionVoteWhereInput | Prisma.SuggestionVoteWhereInput[]
  OR?: Prisma.SuggestionVoteWhereInput[]
  NOT?: Prisma.SuggestionVoteWhereInput | Prisma.SuggestionVoteWhereInput[]
  type?: Prisma.EnumSuggestionVoteTypeFilter<"SuggestionVote"> | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFilter<"SuggestionVote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SuggestionVote"> | Date | string
  createdById?: Prisma.StringFilter<"SuggestionVote"> | string
  suggestionId?: Prisma.StringFilter<"SuggestionVote"> | string
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  suggestion?: Prisma.XOR<Prisma.SuggestionScalarRelationFilter, Prisma.SuggestionWhereInput>
}, "id" | "createdById_suggestionId">

export type SuggestionVoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
  _count?: Prisma.SuggestionVoteCountOrderByAggregateInput
  _max?: Prisma.SuggestionVoteMaxOrderByAggregateInput
  _min?: Prisma.SuggestionVoteMinOrderByAggregateInput
}

export type SuggestionVoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.SuggestionVoteScalarWhereWithAggregatesInput | Prisma.SuggestionVoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.SuggestionVoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SuggestionVoteScalarWhereWithAggregatesInput | Prisma.SuggestionVoteScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SuggestionVote"> | string
  type?: Prisma.EnumSuggestionVoteTypeWithAggregatesFilter<"SuggestionVote"> | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SuggestionVote"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SuggestionVote"> | Date | string
  createdById?: Prisma.StringWithAggregatesFilter<"SuggestionVote"> | string
  suggestionId?: Prisma.StringWithAggregatesFilter<"SuggestionVote"> | string
}

export type SuggestionVoteCreateInput = {
  id?: string
  type: $Enums.SuggestionVoteType
  createdAt?: Date | string
  updatedAt?: Date | string
  createdBy: Prisma.UserCreateNestedOneWithoutSuggestionVotesInput
  suggestion: Prisma.SuggestionCreateNestedOneWithoutVotesInput
}

export type SuggestionVoteUncheckedCreateInput = {
  id?: string
  type: $Enums.SuggestionVoteType
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
  suggestionId: string
}

export type SuggestionVoteUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneRequiredWithoutSuggestionVotesNestedInput
  suggestion?: Prisma.SuggestionUpdateOneRequiredWithoutVotesNestedInput
}

export type SuggestionVoteUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
  suggestionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionVoteCreateManyInput = {
  id?: string
  type: $Enums.SuggestionVoteType
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
  suggestionId: string
}

export type SuggestionVoteUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SuggestionVoteUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
  suggestionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionVoteListRelationFilter = {
  every?: Prisma.SuggestionVoteWhereInput
  some?: Prisma.SuggestionVoteWhereInput
  none?: Prisma.SuggestionVoteWhereInput
}

export type SuggestionVoteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SuggestionVoteOrderByRelevanceInput = {
  fields: Prisma.SuggestionVoteOrderByRelevanceFieldEnum | Prisma.SuggestionVoteOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type SuggestionVoteCreatedByIdSuggestionIdCompoundUniqueInput = {
  createdById: string
  suggestionId: string
}

export type SuggestionVoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
}

export type SuggestionVoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
}

export type SuggestionVoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
}

export type SuggestionVoteCreateNestedManyWithoutSuggestionInput = {
  create?: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutSuggestionInput, Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput> | Prisma.SuggestionVoteCreateWithoutSuggestionInput[] | Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput[]
  connectOrCreate?: Prisma.SuggestionVoteCreateOrConnectWithoutSuggestionInput | Prisma.SuggestionVoteCreateOrConnectWithoutSuggestionInput[]
  createMany?: Prisma.SuggestionVoteCreateManySuggestionInputEnvelope
  connect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
}

export type SuggestionVoteUncheckedCreateNestedManyWithoutSuggestionInput = {
  create?: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutSuggestionInput, Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput> | Prisma.SuggestionVoteCreateWithoutSuggestionInput[] | Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput[]
  connectOrCreate?: Prisma.SuggestionVoteCreateOrConnectWithoutSuggestionInput | Prisma.SuggestionVoteCreateOrConnectWithoutSuggestionInput[]
  createMany?: Prisma.SuggestionVoteCreateManySuggestionInputEnvelope
  connect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
}

export type SuggestionVoteUpdateManyWithoutSuggestionNestedInput = {
  create?: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutSuggestionInput, Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput> | Prisma.SuggestionVoteCreateWithoutSuggestionInput[] | Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput[]
  connectOrCreate?: Prisma.SuggestionVoteCreateOrConnectWithoutSuggestionInput | Prisma.SuggestionVoteCreateOrConnectWithoutSuggestionInput[]
  upsert?: Prisma.SuggestionVoteUpsertWithWhereUniqueWithoutSuggestionInput | Prisma.SuggestionVoteUpsertWithWhereUniqueWithoutSuggestionInput[]
  createMany?: Prisma.SuggestionVoteCreateManySuggestionInputEnvelope
  set?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  disconnect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  delete?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  connect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  update?: Prisma.SuggestionVoteUpdateWithWhereUniqueWithoutSuggestionInput | Prisma.SuggestionVoteUpdateWithWhereUniqueWithoutSuggestionInput[]
  updateMany?: Prisma.SuggestionVoteUpdateManyWithWhereWithoutSuggestionInput | Prisma.SuggestionVoteUpdateManyWithWhereWithoutSuggestionInput[]
  deleteMany?: Prisma.SuggestionVoteScalarWhereInput | Prisma.SuggestionVoteScalarWhereInput[]
}

export type SuggestionVoteUncheckedUpdateManyWithoutSuggestionNestedInput = {
  create?: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutSuggestionInput, Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput> | Prisma.SuggestionVoteCreateWithoutSuggestionInput[] | Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput[]
  connectOrCreate?: Prisma.SuggestionVoteCreateOrConnectWithoutSuggestionInput | Prisma.SuggestionVoteCreateOrConnectWithoutSuggestionInput[]
  upsert?: Prisma.SuggestionVoteUpsertWithWhereUniqueWithoutSuggestionInput | Prisma.SuggestionVoteUpsertWithWhereUniqueWithoutSuggestionInput[]
  createMany?: Prisma.SuggestionVoteCreateManySuggestionInputEnvelope
  set?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  disconnect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  delete?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  connect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  update?: Prisma.SuggestionVoteUpdateWithWhereUniqueWithoutSuggestionInput | Prisma.SuggestionVoteUpdateWithWhereUniqueWithoutSuggestionInput[]
  updateMany?: Prisma.SuggestionVoteUpdateManyWithWhereWithoutSuggestionInput | Prisma.SuggestionVoteUpdateManyWithWhereWithoutSuggestionInput[]
  deleteMany?: Prisma.SuggestionVoteScalarWhereInput | Prisma.SuggestionVoteScalarWhereInput[]
}

export type EnumSuggestionVoteTypeFieldUpdateOperationsInput = {
  set?: $Enums.SuggestionVoteType
}

export type SuggestionVoteCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutCreatedByInput, Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput> | Prisma.SuggestionVoteCreateWithoutCreatedByInput[] | Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.SuggestionVoteCreateOrConnectWithoutCreatedByInput | Prisma.SuggestionVoteCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.SuggestionVoteCreateManyCreatedByInputEnvelope
  connect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
}

export type SuggestionVoteUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutCreatedByInput, Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput> | Prisma.SuggestionVoteCreateWithoutCreatedByInput[] | Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.SuggestionVoteCreateOrConnectWithoutCreatedByInput | Prisma.SuggestionVoteCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.SuggestionVoteCreateManyCreatedByInputEnvelope
  connect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
}

export type SuggestionVoteUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutCreatedByInput, Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput> | Prisma.SuggestionVoteCreateWithoutCreatedByInput[] | Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.SuggestionVoteCreateOrConnectWithoutCreatedByInput | Prisma.SuggestionVoteCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.SuggestionVoteUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.SuggestionVoteUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.SuggestionVoteCreateManyCreatedByInputEnvelope
  set?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  disconnect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  delete?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  connect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  update?: Prisma.SuggestionVoteUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.SuggestionVoteUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.SuggestionVoteUpdateManyWithWhereWithoutCreatedByInput | Prisma.SuggestionVoteUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.SuggestionVoteScalarWhereInput | Prisma.SuggestionVoteScalarWhereInput[]
}

export type SuggestionVoteUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutCreatedByInput, Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput> | Prisma.SuggestionVoteCreateWithoutCreatedByInput[] | Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.SuggestionVoteCreateOrConnectWithoutCreatedByInput | Prisma.SuggestionVoteCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.SuggestionVoteUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.SuggestionVoteUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.SuggestionVoteCreateManyCreatedByInputEnvelope
  set?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  disconnect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  delete?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  connect?: Prisma.SuggestionVoteWhereUniqueInput | Prisma.SuggestionVoteWhereUniqueInput[]
  update?: Prisma.SuggestionVoteUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.SuggestionVoteUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.SuggestionVoteUpdateManyWithWhereWithoutCreatedByInput | Prisma.SuggestionVoteUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.SuggestionVoteScalarWhereInput | Prisma.SuggestionVoteScalarWhereInput[]
}

export type SuggestionVoteCreateWithoutSuggestionInput = {
  id?: string
  type: $Enums.SuggestionVoteType
  createdAt?: Date | string
  updatedAt?: Date | string
  createdBy: Prisma.UserCreateNestedOneWithoutSuggestionVotesInput
}

export type SuggestionVoteUncheckedCreateWithoutSuggestionInput = {
  id?: string
  type: $Enums.SuggestionVoteType
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
}

export type SuggestionVoteCreateOrConnectWithoutSuggestionInput = {
  where: Prisma.SuggestionVoteWhereUniqueInput
  create: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutSuggestionInput, Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput>
}

export type SuggestionVoteCreateManySuggestionInputEnvelope = {
  data: Prisma.SuggestionVoteCreateManySuggestionInput | Prisma.SuggestionVoteCreateManySuggestionInput[]
  skipDuplicates?: boolean
}

export type SuggestionVoteUpsertWithWhereUniqueWithoutSuggestionInput = {
  where: Prisma.SuggestionVoteWhereUniqueInput
  update: Prisma.XOR<Prisma.SuggestionVoteUpdateWithoutSuggestionInput, Prisma.SuggestionVoteUncheckedUpdateWithoutSuggestionInput>
  create: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutSuggestionInput, Prisma.SuggestionVoteUncheckedCreateWithoutSuggestionInput>
}

export type SuggestionVoteUpdateWithWhereUniqueWithoutSuggestionInput = {
  where: Prisma.SuggestionVoteWhereUniqueInput
  data: Prisma.XOR<Prisma.SuggestionVoteUpdateWithoutSuggestionInput, Prisma.SuggestionVoteUncheckedUpdateWithoutSuggestionInput>
}

export type SuggestionVoteUpdateManyWithWhereWithoutSuggestionInput = {
  where: Prisma.SuggestionVoteScalarWhereInput
  data: Prisma.XOR<Prisma.SuggestionVoteUpdateManyMutationInput, Prisma.SuggestionVoteUncheckedUpdateManyWithoutSuggestionInput>
}

export type SuggestionVoteScalarWhereInput = {
  AND?: Prisma.SuggestionVoteScalarWhereInput | Prisma.SuggestionVoteScalarWhereInput[]
  OR?: Prisma.SuggestionVoteScalarWhereInput[]
  NOT?: Prisma.SuggestionVoteScalarWhereInput | Prisma.SuggestionVoteScalarWhereInput[]
  id?: Prisma.StringFilter<"SuggestionVote"> | string
  type?: Prisma.EnumSuggestionVoteTypeFilter<"SuggestionVote"> | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFilter<"SuggestionVote"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SuggestionVote"> | Date | string
  createdById?: Prisma.StringFilter<"SuggestionVote"> | string
  suggestionId?: Prisma.StringFilter<"SuggestionVote"> | string
}

export type SuggestionVoteCreateWithoutCreatedByInput = {
  id?: string
  type: $Enums.SuggestionVoteType
  createdAt?: Date | string
  updatedAt?: Date | string
  suggestion: Prisma.SuggestionCreateNestedOneWithoutVotesInput
}

export type SuggestionVoteUncheckedCreateWithoutCreatedByInput = {
  id?: string
  type: $Enums.SuggestionVoteType
  createdAt?: Date | string
  updatedAt?: Date | string
  suggestionId: string
}

export type SuggestionVoteCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.SuggestionVoteWhereUniqueInput
  create: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutCreatedByInput, Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput>
}

export type SuggestionVoteCreateManyCreatedByInputEnvelope = {
  data: Prisma.SuggestionVoteCreateManyCreatedByInput | Prisma.SuggestionVoteCreateManyCreatedByInput[]
  skipDuplicates?: boolean
}

export type SuggestionVoteUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.SuggestionVoteWhereUniqueInput
  update: Prisma.XOR<Prisma.SuggestionVoteUpdateWithoutCreatedByInput, Prisma.SuggestionVoteUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.SuggestionVoteCreateWithoutCreatedByInput, Prisma.SuggestionVoteUncheckedCreateWithoutCreatedByInput>
}

export type SuggestionVoteUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.SuggestionVoteWhereUniqueInput
  data: Prisma.XOR<Prisma.SuggestionVoteUpdateWithoutCreatedByInput, Prisma.SuggestionVoteUncheckedUpdateWithoutCreatedByInput>
}

export type SuggestionVoteUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.SuggestionVoteScalarWhereInput
  data: Prisma.XOR<Prisma.SuggestionVoteUpdateManyMutationInput, Prisma.SuggestionVoteUncheckedUpdateManyWithoutCreatedByInput>
}

export type SuggestionVoteCreateManySuggestionInput = {
  id?: string
  type: $Enums.SuggestionVoteType
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
}

export type SuggestionVoteUpdateWithoutSuggestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneRequiredWithoutSuggestionVotesNestedInput
}

export type SuggestionVoteUncheckedUpdateWithoutSuggestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionVoteUncheckedUpdateManyWithoutSuggestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionVoteCreateManyCreatedByInput = {
  id?: string
  type: $Enums.SuggestionVoteType
  createdAt?: Date | string
  updatedAt?: Date | string
  suggestionId: string
}

export type SuggestionVoteUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  suggestion?: Prisma.SuggestionUpdateOneRequiredWithoutVotesNestedInput
}

export type SuggestionVoteUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  suggestionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionVoteUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSuggestionVoteTypeFieldUpdateOperationsInput | $Enums.SuggestionVoteType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  suggestionId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SuggestionVoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  suggestionId?: boolean
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["suggestionVote"]>

export type SuggestionVoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  suggestionId?: boolean
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["suggestionVote"]>

export type SuggestionVoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  suggestionId?: boolean
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["suggestionVote"]>

export type SuggestionVoteSelectScalar = {
  id?: boolean
  type?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  suggestionId?: boolean
}

export type SuggestionVoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "createdAt" | "updatedAt" | "createdById" | "suggestionId", ExtArgs["result"]["suggestionVote"]>
export type SuggestionVoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}
export type SuggestionVoteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}
export type SuggestionVoteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}

export type $SuggestionVotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SuggestionVote"
  objects: {
    createdBy: Prisma.$UserPayload<ExtArgs>
    suggestion: Prisma.$SuggestionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: $Enums.SuggestionVoteType
    createdAt: Date
    updatedAt: Date
    createdById: string
    suggestionId: string
  }, ExtArgs["result"]["suggestionVote"]>
  composites: {}
}

export type SuggestionVoteGetPayload<S extends boolean | null | undefined | SuggestionVoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload, S>

export type SuggestionVoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SuggestionVoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SuggestionVoteCountAggregateInputType | true
  }

export interface SuggestionVoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SuggestionVote'], meta: { name: 'SuggestionVote' } }
  /**
   * Find zero or one SuggestionVote that matches the filter.
   * @param {SuggestionVoteFindUniqueArgs} args - Arguments to find a SuggestionVote
   * @example
   * // Get one SuggestionVote
   * const suggestionVote = await prisma.suggestionVote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SuggestionVoteFindUniqueArgs>(args: Prisma.SelectSubset<T, SuggestionVoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SuggestionVoteClient<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SuggestionVote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SuggestionVoteFindUniqueOrThrowArgs} args - Arguments to find a SuggestionVote
   * @example
   * // Get one SuggestionVote
   * const suggestionVote = await prisma.suggestionVote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SuggestionVoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SuggestionVoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SuggestionVoteClient<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SuggestionVote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionVoteFindFirstArgs} args - Arguments to find a SuggestionVote
   * @example
   * // Get one SuggestionVote
   * const suggestionVote = await prisma.suggestionVote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SuggestionVoteFindFirstArgs>(args?: Prisma.SelectSubset<T, SuggestionVoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__SuggestionVoteClient<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SuggestionVote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionVoteFindFirstOrThrowArgs} args - Arguments to find a SuggestionVote
   * @example
   * // Get one SuggestionVote
   * const suggestionVote = await prisma.suggestionVote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SuggestionVoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SuggestionVoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SuggestionVoteClient<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SuggestionVotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionVoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SuggestionVotes
   * const suggestionVotes = await prisma.suggestionVote.findMany()
   * 
   * // Get first 10 SuggestionVotes
   * const suggestionVotes = await prisma.suggestionVote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const suggestionVoteWithIdOnly = await prisma.suggestionVote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SuggestionVoteFindManyArgs>(args?: Prisma.SelectSubset<T, SuggestionVoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SuggestionVote.
   * @param {SuggestionVoteCreateArgs} args - Arguments to create a SuggestionVote.
   * @example
   * // Create one SuggestionVote
   * const SuggestionVote = await prisma.suggestionVote.create({
   *   data: {
   *     // ... data to create a SuggestionVote
   *   }
   * })
   * 
   */
  create<T extends SuggestionVoteCreateArgs>(args: Prisma.SelectSubset<T, SuggestionVoteCreateArgs<ExtArgs>>): Prisma.Prisma__SuggestionVoteClient<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SuggestionVotes.
   * @param {SuggestionVoteCreateManyArgs} args - Arguments to create many SuggestionVotes.
   * @example
   * // Create many SuggestionVotes
   * const suggestionVote = await prisma.suggestionVote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SuggestionVoteCreateManyArgs>(args?: Prisma.SelectSubset<T, SuggestionVoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SuggestionVotes and returns the data saved in the database.
   * @param {SuggestionVoteCreateManyAndReturnArgs} args - Arguments to create many SuggestionVotes.
   * @example
   * // Create many SuggestionVotes
   * const suggestionVote = await prisma.suggestionVote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SuggestionVotes and only return the `id`
   * const suggestionVoteWithIdOnly = await prisma.suggestionVote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SuggestionVoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SuggestionVoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SuggestionVote.
   * @param {SuggestionVoteDeleteArgs} args - Arguments to delete one SuggestionVote.
   * @example
   * // Delete one SuggestionVote
   * const SuggestionVote = await prisma.suggestionVote.delete({
   *   where: {
   *     // ... filter to delete one SuggestionVote
   *   }
   * })
   * 
   */
  delete<T extends SuggestionVoteDeleteArgs>(args: Prisma.SelectSubset<T, SuggestionVoteDeleteArgs<ExtArgs>>): Prisma.Prisma__SuggestionVoteClient<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SuggestionVote.
   * @param {SuggestionVoteUpdateArgs} args - Arguments to update one SuggestionVote.
   * @example
   * // Update one SuggestionVote
   * const suggestionVote = await prisma.suggestionVote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SuggestionVoteUpdateArgs>(args: Prisma.SelectSubset<T, SuggestionVoteUpdateArgs<ExtArgs>>): Prisma.Prisma__SuggestionVoteClient<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SuggestionVotes.
   * @param {SuggestionVoteDeleteManyArgs} args - Arguments to filter SuggestionVotes to delete.
   * @example
   * // Delete a few SuggestionVotes
   * const { count } = await prisma.suggestionVote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SuggestionVoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, SuggestionVoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SuggestionVotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionVoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SuggestionVotes
   * const suggestionVote = await prisma.suggestionVote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SuggestionVoteUpdateManyArgs>(args: Prisma.SelectSubset<T, SuggestionVoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SuggestionVotes and returns the data updated in the database.
   * @param {SuggestionVoteUpdateManyAndReturnArgs} args - Arguments to update many SuggestionVotes.
   * @example
   * // Update many SuggestionVotes
   * const suggestionVote = await prisma.suggestionVote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SuggestionVotes and only return the `id`
   * const suggestionVoteWithIdOnly = await prisma.suggestionVote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SuggestionVoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SuggestionVoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SuggestionVote.
   * @param {SuggestionVoteUpsertArgs} args - Arguments to update or create a SuggestionVote.
   * @example
   * // Update or create a SuggestionVote
   * const suggestionVote = await prisma.suggestionVote.upsert({
   *   create: {
   *     // ... data to create a SuggestionVote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SuggestionVote we want to update
   *   }
   * })
   */
  upsert<T extends SuggestionVoteUpsertArgs>(args: Prisma.SelectSubset<T, SuggestionVoteUpsertArgs<ExtArgs>>): Prisma.Prisma__SuggestionVoteClient<runtime.Types.Result.GetResult<Prisma.$SuggestionVotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SuggestionVotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionVoteCountArgs} args - Arguments to filter SuggestionVotes to count.
   * @example
   * // Count the number of SuggestionVotes
   * const count = await prisma.suggestionVote.count({
   *   where: {
   *     // ... the filter for the SuggestionVotes we want to count
   *   }
   * })
  **/
  count<T extends SuggestionVoteCountArgs>(
    args?: Prisma.Subset<T, SuggestionVoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SuggestionVoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SuggestionVote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionVoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SuggestionVoteAggregateArgs>(args: Prisma.Subset<T, SuggestionVoteAggregateArgs>): Prisma.PrismaPromise<GetSuggestionVoteAggregateType<T>>

  /**
   * Group by SuggestionVote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionVoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SuggestionVoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SuggestionVoteGroupByArgs['orderBy'] }
      : { orderBy?: SuggestionVoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SuggestionVoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSuggestionVoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SuggestionVote model
 */
readonly fields: SuggestionVoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SuggestionVote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SuggestionVoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  createdBy<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  suggestion<T extends Prisma.SuggestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SuggestionDefaultArgs<ExtArgs>>): Prisma.Prisma__SuggestionClient<runtime.Types.Result.GetResult<Prisma.$SuggestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SuggestionVote model
 */
export interface SuggestionVoteFieldRefs {
  readonly id: Prisma.FieldRef<"SuggestionVote", 'String'>
  readonly type: Prisma.FieldRef<"SuggestionVote", 'SuggestionVoteType'>
  readonly createdAt: Prisma.FieldRef<"SuggestionVote", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SuggestionVote", 'DateTime'>
  readonly createdById: Prisma.FieldRef<"SuggestionVote", 'String'>
  readonly suggestionId: Prisma.FieldRef<"SuggestionVote", 'String'>
}
    

// Custom InputTypes
/**
 * SuggestionVote findUnique
 */
export type SuggestionVoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionVote to fetch.
   */
  where: Prisma.SuggestionVoteWhereUniqueInput
}

/**
 * SuggestionVote findUniqueOrThrow
 */
export type SuggestionVoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionVote to fetch.
   */
  where: Prisma.SuggestionVoteWhereUniqueInput
}

/**
 * SuggestionVote findFirst
 */
export type SuggestionVoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionVote to fetch.
   */
  where?: Prisma.SuggestionVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SuggestionVotes to fetch.
   */
  orderBy?: Prisma.SuggestionVoteOrderByWithRelationInput | Prisma.SuggestionVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SuggestionVotes.
   */
  cursor?: Prisma.SuggestionVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SuggestionVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SuggestionVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SuggestionVotes.
   */
  distinct?: Prisma.SuggestionVoteScalarFieldEnum | Prisma.SuggestionVoteScalarFieldEnum[]
}

/**
 * SuggestionVote findFirstOrThrow
 */
export type SuggestionVoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionVote to fetch.
   */
  where?: Prisma.SuggestionVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SuggestionVotes to fetch.
   */
  orderBy?: Prisma.SuggestionVoteOrderByWithRelationInput | Prisma.SuggestionVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SuggestionVotes.
   */
  cursor?: Prisma.SuggestionVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SuggestionVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SuggestionVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SuggestionVotes.
   */
  distinct?: Prisma.SuggestionVoteScalarFieldEnum | Prisma.SuggestionVoteScalarFieldEnum[]
}

/**
 * SuggestionVote findMany
 */
export type SuggestionVoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionVotes to fetch.
   */
  where?: Prisma.SuggestionVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SuggestionVotes to fetch.
   */
  orderBy?: Prisma.SuggestionVoteOrderByWithRelationInput | Prisma.SuggestionVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SuggestionVotes.
   */
  cursor?: Prisma.SuggestionVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SuggestionVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SuggestionVotes.
   */
  skip?: number
  distinct?: Prisma.SuggestionVoteScalarFieldEnum | Prisma.SuggestionVoteScalarFieldEnum[]
}

/**
 * SuggestionVote create
 */
export type SuggestionVoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
  /**
   * The data needed to create a SuggestionVote.
   */
  data: Prisma.XOR<Prisma.SuggestionVoteCreateInput, Prisma.SuggestionVoteUncheckedCreateInput>
}

/**
 * SuggestionVote createMany
 */
export type SuggestionVoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SuggestionVotes.
   */
  data: Prisma.SuggestionVoteCreateManyInput | Prisma.SuggestionVoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SuggestionVote createManyAndReturn
 */
export type SuggestionVoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * The data used to create many SuggestionVotes.
   */
  data: Prisma.SuggestionVoteCreateManyInput | Prisma.SuggestionVoteCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SuggestionVote update
 */
export type SuggestionVoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
  /**
   * The data needed to update a SuggestionVote.
   */
  data: Prisma.XOR<Prisma.SuggestionVoteUpdateInput, Prisma.SuggestionVoteUncheckedUpdateInput>
  /**
   * Choose, which SuggestionVote to update.
   */
  where: Prisma.SuggestionVoteWhereUniqueInput
}

/**
 * SuggestionVote updateMany
 */
export type SuggestionVoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SuggestionVotes.
   */
  data: Prisma.XOR<Prisma.SuggestionVoteUpdateManyMutationInput, Prisma.SuggestionVoteUncheckedUpdateManyInput>
  /**
   * Filter which SuggestionVotes to update
   */
  where?: Prisma.SuggestionVoteWhereInput
  /**
   * Limit how many SuggestionVotes to update.
   */
  limit?: number
}

/**
 * SuggestionVote updateManyAndReturn
 */
export type SuggestionVoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * The data used to update SuggestionVotes.
   */
  data: Prisma.XOR<Prisma.SuggestionVoteUpdateManyMutationInput, Prisma.SuggestionVoteUncheckedUpdateManyInput>
  /**
   * Filter which SuggestionVotes to update
   */
  where?: Prisma.SuggestionVoteWhereInput
  /**
   * Limit how many SuggestionVotes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SuggestionVote upsert
 */
export type SuggestionVoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
  /**
   * The filter to search for the SuggestionVote to update in case it exists.
   */
  where: Prisma.SuggestionVoteWhereUniqueInput
  /**
   * In case the SuggestionVote found by the `where` argument doesn't exist, create a new SuggestionVote with this data.
   */
  create: Prisma.XOR<Prisma.SuggestionVoteCreateInput, Prisma.SuggestionVoteUncheckedCreateInput>
  /**
   * In case the SuggestionVote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SuggestionVoteUpdateInput, Prisma.SuggestionVoteUncheckedUpdateInput>
}

/**
 * SuggestionVote delete
 */
export type SuggestionVoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
  /**
   * Filter which SuggestionVote to delete.
   */
  where: Prisma.SuggestionVoteWhereUniqueInput
}

/**
 * SuggestionVote deleteMany
 */
export type SuggestionVoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SuggestionVotes to delete
   */
  where?: Prisma.SuggestionVoteWhereInput
  /**
   * Limit how many SuggestionVotes to delete.
   */
  limit?: number
}

/**
 * SuggestionVote without action
 */
export type SuggestionVoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionVote
   */
  select?: Prisma.SuggestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionVote
   */
  omit?: Prisma.SuggestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionVoteInclude<ExtArgs> | null
}
