
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `SuggestionComment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SuggestionComment
 * 
 */
export type SuggestionCommentModel = runtime.Types.Result.DefaultSelection<Prisma.$SuggestionCommentPayload>

export type AggregateSuggestionComment = {
  _count: SuggestionCommentCountAggregateOutputType | null
  _min: SuggestionCommentMinAggregateOutputType | null
  _max: SuggestionCommentMaxAggregateOutputType | null
}

export type SuggestionCommentMinAggregateOutputType = {
  id: string | null
  comment: string | null
  isAnonymous: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  createdById: string | null
  suggestionId: string | null
}

export type SuggestionCommentMaxAggregateOutputType = {
  id: string | null
  comment: string | null
  isAnonymous: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
  createdById: string | null
  suggestionId: string | null
}

export type SuggestionCommentCountAggregateOutputType = {
  id: number
  comment: number
  isAnonymous: number
  createdAt: number
  updatedAt: number
  createdById: number
  suggestionId: number
  _all: number
}


export type SuggestionCommentMinAggregateInputType = {
  id?: true
  comment?: true
  isAnonymous?: true
  createdAt?: true
  updatedAt?: true
  createdById?: true
  suggestionId?: true
}

export type SuggestionCommentMaxAggregateInputType = {
  id?: true
  comment?: true
  isAnonymous?: true
  createdAt?: true
  updatedAt?: true
  createdById?: true
  suggestionId?: true
}

export type SuggestionCommentCountAggregateInputType = {
  id?: true
  comment?: true
  isAnonymous?: true
  createdAt?: true
  updatedAt?: true
  createdById?: true
  suggestionId?: true
  _all?: true
}

export type SuggestionCommentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SuggestionComment to aggregate.
   */
  where?: Prisma.SuggestionCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SuggestionComments to fetch.
   */
  orderBy?: Prisma.SuggestionCommentOrderByWithRelationInput | Prisma.SuggestionCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SuggestionCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SuggestionComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SuggestionComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SuggestionComments
  **/
  _count?: true | SuggestionCommentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SuggestionCommentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SuggestionCommentMaxAggregateInputType
}

export type GetSuggestionCommentAggregateType<T extends SuggestionCommentAggregateArgs> = {
      [P in keyof T & keyof AggregateSuggestionComment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSuggestionComment[P]>
    : Prisma.GetScalarType<T[P], AggregateSuggestionComment[P]>
}




export type SuggestionCommentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SuggestionCommentWhereInput
  orderBy?: Prisma.SuggestionCommentOrderByWithAggregationInput | Prisma.SuggestionCommentOrderByWithAggregationInput[]
  by: Prisma.SuggestionCommentScalarFieldEnum[] | Prisma.SuggestionCommentScalarFieldEnum
  having?: Prisma.SuggestionCommentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SuggestionCommentCountAggregateInputType | true
  _min?: SuggestionCommentMinAggregateInputType
  _max?: SuggestionCommentMaxAggregateInputType
}

export type SuggestionCommentGroupByOutputType = {
  id: string
  comment: string
  isAnonymous: boolean
  createdAt: Date
  updatedAt: Date
  createdById: string
  suggestionId: string
  _count: SuggestionCommentCountAggregateOutputType | null
  _min: SuggestionCommentMinAggregateOutputType | null
  _max: SuggestionCommentMaxAggregateOutputType | null
}

type GetSuggestionCommentGroupByPayload<T extends SuggestionCommentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SuggestionCommentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SuggestionCommentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SuggestionCommentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SuggestionCommentGroupByOutputType[P]>
      }
    >
  > 



export type SuggestionCommentWhereInput = {
  AND?: Prisma.SuggestionCommentWhereInput | Prisma.SuggestionCommentWhereInput[]
  OR?: Prisma.SuggestionCommentWhereInput[]
  NOT?: Prisma.SuggestionCommentWhereInput | Prisma.SuggestionCommentWhereInput[]
  id?: Prisma.StringFilter<"SuggestionComment"> | string
  comment?: Prisma.StringFilter<"SuggestionComment"> | string
  isAnonymous?: Prisma.BoolFilter<"SuggestionComment"> | boolean
  createdAt?: Prisma.DateTimeFilter<"SuggestionComment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SuggestionComment"> | Date | string
  createdById?: Prisma.StringFilter<"SuggestionComment"> | string
  suggestionId?: Prisma.StringFilter<"SuggestionComment"> | string
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  suggestion?: Prisma.XOR<Prisma.SuggestionScalarRelationFilter, Prisma.SuggestionWhereInput>
}

export type SuggestionCommentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
  createdBy?: Prisma.UserOrderByWithRelationInput
  suggestion?: Prisma.SuggestionOrderByWithRelationInput
  _relevance?: Prisma.SuggestionCommentOrderByRelevanceInput
}

export type SuggestionCommentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SuggestionCommentWhereInput | Prisma.SuggestionCommentWhereInput[]
  OR?: Prisma.SuggestionCommentWhereInput[]
  NOT?: Prisma.SuggestionCommentWhereInput | Prisma.SuggestionCommentWhereInput[]
  comment?: Prisma.StringFilter<"SuggestionComment"> | string
  isAnonymous?: Prisma.BoolFilter<"SuggestionComment"> | boolean
  createdAt?: Prisma.DateTimeFilter<"SuggestionComment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SuggestionComment"> | Date | string
  createdById?: Prisma.StringFilter<"SuggestionComment"> | string
  suggestionId?: Prisma.StringFilter<"SuggestionComment"> | string
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  suggestion?: Prisma.XOR<Prisma.SuggestionScalarRelationFilter, Prisma.SuggestionWhereInput>
}, "id">

export type SuggestionCommentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
  _count?: Prisma.SuggestionCommentCountOrderByAggregateInput
  _max?: Prisma.SuggestionCommentMaxOrderByAggregateInput
  _min?: Prisma.SuggestionCommentMinOrderByAggregateInput
}

export type SuggestionCommentScalarWhereWithAggregatesInput = {
  AND?: Prisma.SuggestionCommentScalarWhereWithAggregatesInput | Prisma.SuggestionCommentScalarWhereWithAggregatesInput[]
  OR?: Prisma.SuggestionCommentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SuggestionCommentScalarWhereWithAggregatesInput | Prisma.SuggestionCommentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SuggestionComment"> | string
  comment?: Prisma.StringWithAggregatesFilter<"SuggestionComment"> | string
  isAnonymous?: Prisma.BoolWithAggregatesFilter<"SuggestionComment"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SuggestionComment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SuggestionComment"> | Date | string
  createdById?: Prisma.StringWithAggregatesFilter<"SuggestionComment"> | string
  suggestionId?: Prisma.StringWithAggregatesFilter<"SuggestionComment"> | string
}

export type SuggestionCommentCreateInput = {
  id?: string
  comment: string
  isAnonymous?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdBy: Prisma.UserCreateNestedOneWithoutSuggestionCommentInput
  suggestion: Prisma.SuggestionCreateNestedOneWithoutCommentsInput
}

export type SuggestionCommentUncheckedCreateInput = {
  id?: string
  comment: string
  isAnonymous?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
  suggestionId: string
}

export type SuggestionCommentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneRequiredWithoutSuggestionCommentNestedInput
  suggestion?: Prisma.SuggestionUpdateOneRequiredWithoutCommentsNestedInput
}

export type SuggestionCommentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
  suggestionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionCommentCreateManyInput = {
  id?: string
  comment: string
  isAnonymous?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
  suggestionId: string
}

export type SuggestionCommentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SuggestionCommentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
  suggestionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionCommentListRelationFilter = {
  every?: Prisma.SuggestionCommentWhereInput
  some?: Prisma.SuggestionCommentWhereInput
  none?: Prisma.SuggestionCommentWhereInput
}

export type SuggestionCommentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SuggestionCommentOrderByRelevanceInput = {
  fields: Prisma.SuggestionCommentOrderByRelevanceFieldEnum | Prisma.SuggestionCommentOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type SuggestionCommentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
}

export type SuggestionCommentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
}

export type SuggestionCommentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  comment?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  suggestionId?: Prisma.SortOrder
}

export type SuggestionCommentCreateNestedManyWithoutSuggestionInput = {
  create?: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutSuggestionInput, Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput> | Prisma.SuggestionCommentCreateWithoutSuggestionInput[] | Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput[]
  connectOrCreate?: Prisma.SuggestionCommentCreateOrConnectWithoutSuggestionInput | Prisma.SuggestionCommentCreateOrConnectWithoutSuggestionInput[]
  createMany?: Prisma.SuggestionCommentCreateManySuggestionInputEnvelope
  connect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
}

export type SuggestionCommentUncheckedCreateNestedManyWithoutSuggestionInput = {
  create?: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutSuggestionInput, Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput> | Prisma.SuggestionCommentCreateWithoutSuggestionInput[] | Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput[]
  connectOrCreate?: Prisma.SuggestionCommentCreateOrConnectWithoutSuggestionInput | Prisma.SuggestionCommentCreateOrConnectWithoutSuggestionInput[]
  createMany?: Prisma.SuggestionCommentCreateManySuggestionInputEnvelope
  connect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
}

export type SuggestionCommentUpdateManyWithoutSuggestionNestedInput = {
  create?: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutSuggestionInput, Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput> | Prisma.SuggestionCommentCreateWithoutSuggestionInput[] | Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput[]
  connectOrCreate?: Prisma.SuggestionCommentCreateOrConnectWithoutSuggestionInput | Prisma.SuggestionCommentCreateOrConnectWithoutSuggestionInput[]
  upsert?: Prisma.SuggestionCommentUpsertWithWhereUniqueWithoutSuggestionInput | Prisma.SuggestionCommentUpsertWithWhereUniqueWithoutSuggestionInput[]
  createMany?: Prisma.SuggestionCommentCreateManySuggestionInputEnvelope
  set?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  disconnect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  delete?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  connect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  update?: Prisma.SuggestionCommentUpdateWithWhereUniqueWithoutSuggestionInput | Prisma.SuggestionCommentUpdateWithWhereUniqueWithoutSuggestionInput[]
  updateMany?: Prisma.SuggestionCommentUpdateManyWithWhereWithoutSuggestionInput | Prisma.SuggestionCommentUpdateManyWithWhereWithoutSuggestionInput[]
  deleteMany?: Prisma.SuggestionCommentScalarWhereInput | Prisma.SuggestionCommentScalarWhereInput[]
}

export type SuggestionCommentUncheckedUpdateManyWithoutSuggestionNestedInput = {
  create?: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutSuggestionInput, Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput> | Prisma.SuggestionCommentCreateWithoutSuggestionInput[] | Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput[]
  connectOrCreate?: Prisma.SuggestionCommentCreateOrConnectWithoutSuggestionInput | Prisma.SuggestionCommentCreateOrConnectWithoutSuggestionInput[]
  upsert?: Prisma.SuggestionCommentUpsertWithWhereUniqueWithoutSuggestionInput | Prisma.SuggestionCommentUpsertWithWhereUniqueWithoutSuggestionInput[]
  createMany?: Prisma.SuggestionCommentCreateManySuggestionInputEnvelope
  set?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  disconnect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  delete?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  connect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  update?: Prisma.SuggestionCommentUpdateWithWhereUniqueWithoutSuggestionInput | Prisma.SuggestionCommentUpdateWithWhereUniqueWithoutSuggestionInput[]
  updateMany?: Prisma.SuggestionCommentUpdateManyWithWhereWithoutSuggestionInput | Prisma.SuggestionCommentUpdateManyWithWhereWithoutSuggestionInput[]
  deleteMany?: Prisma.SuggestionCommentScalarWhereInput | Prisma.SuggestionCommentScalarWhereInput[]
}

export type SuggestionCommentCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutCreatedByInput, Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput> | Prisma.SuggestionCommentCreateWithoutCreatedByInput[] | Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.SuggestionCommentCreateOrConnectWithoutCreatedByInput | Prisma.SuggestionCommentCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.SuggestionCommentCreateManyCreatedByInputEnvelope
  connect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
}

export type SuggestionCommentUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutCreatedByInput, Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput> | Prisma.SuggestionCommentCreateWithoutCreatedByInput[] | Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.SuggestionCommentCreateOrConnectWithoutCreatedByInput | Prisma.SuggestionCommentCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.SuggestionCommentCreateManyCreatedByInputEnvelope
  connect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
}

export type SuggestionCommentUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutCreatedByInput, Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput> | Prisma.SuggestionCommentCreateWithoutCreatedByInput[] | Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.SuggestionCommentCreateOrConnectWithoutCreatedByInput | Prisma.SuggestionCommentCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.SuggestionCommentUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.SuggestionCommentUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.SuggestionCommentCreateManyCreatedByInputEnvelope
  set?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  disconnect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  delete?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  connect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  update?: Prisma.SuggestionCommentUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.SuggestionCommentUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.SuggestionCommentUpdateManyWithWhereWithoutCreatedByInput | Prisma.SuggestionCommentUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.SuggestionCommentScalarWhereInput | Prisma.SuggestionCommentScalarWhereInput[]
}

export type SuggestionCommentUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutCreatedByInput, Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput> | Prisma.SuggestionCommentCreateWithoutCreatedByInput[] | Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.SuggestionCommentCreateOrConnectWithoutCreatedByInput | Prisma.SuggestionCommentCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.SuggestionCommentUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.SuggestionCommentUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.SuggestionCommentCreateManyCreatedByInputEnvelope
  set?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  disconnect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  delete?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  connect?: Prisma.SuggestionCommentWhereUniqueInput | Prisma.SuggestionCommentWhereUniqueInput[]
  update?: Prisma.SuggestionCommentUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.SuggestionCommentUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.SuggestionCommentUpdateManyWithWhereWithoutCreatedByInput | Prisma.SuggestionCommentUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.SuggestionCommentScalarWhereInput | Prisma.SuggestionCommentScalarWhereInput[]
}

export type SuggestionCommentCreateWithoutSuggestionInput = {
  id?: string
  comment: string
  isAnonymous?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdBy: Prisma.UserCreateNestedOneWithoutSuggestionCommentInput
}

export type SuggestionCommentUncheckedCreateWithoutSuggestionInput = {
  id?: string
  comment: string
  isAnonymous?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
}

export type SuggestionCommentCreateOrConnectWithoutSuggestionInput = {
  where: Prisma.SuggestionCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutSuggestionInput, Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput>
}

export type SuggestionCommentCreateManySuggestionInputEnvelope = {
  data: Prisma.SuggestionCommentCreateManySuggestionInput | Prisma.SuggestionCommentCreateManySuggestionInput[]
  skipDuplicates?: boolean
}

export type SuggestionCommentUpsertWithWhereUniqueWithoutSuggestionInput = {
  where: Prisma.SuggestionCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.SuggestionCommentUpdateWithoutSuggestionInput, Prisma.SuggestionCommentUncheckedUpdateWithoutSuggestionInput>
  create: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutSuggestionInput, Prisma.SuggestionCommentUncheckedCreateWithoutSuggestionInput>
}

export type SuggestionCommentUpdateWithWhereUniqueWithoutSuggestionInput = {
  where: Prisma.SuggestionCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.SuggestionCommentUpdateWithoutSuggestionInput, Prisma.SuggestionCommentUncheckedUpdateWithoutSuggestionInput>
}

export type SuggestionCommentUpdateManyWithWhereWithoutSuggestionInput = {
  where: Prisma.SuggestionCommentScalarWhereInput
  data: Prisma.XOR<Prisma.SuggestionCommentUpdateManyMutationInput, Prisma.SuggestionCommentUncheckedUpdateManyWithoutSuggestionInput>
}

export type SuggestionCommentScalarWhereInput = {
  AND?: Prisma.SuggestionCommentScalarWhereInput | Prisma.SuggestionCommentScalarWhereInput[]
  OR?: Prisma.SuggestionCommentScalarWhereInput[]
  NOT?: Prisma.SuggestionCommentScalarWhereInput | Prisma.SuggestionCommentScalarWhereInput[]
  id?: Prisma.StringFilter<"SuggestionComment"> | string
  comment?: Prisma.StringFilter<"SuggestionComment"> | string
  isAnonymous?: Prisma.BoolFilter<"SuggestionComment"> | boolean
  createdAt?: Prisma.DateTimeFilter<"SuggestionComment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SuggestionComment"> | Date | string
  createdById?: Prisma.StringFilter<"SuggestionComment"> | string
  suggestionId?: Prisma.StringFilter<"SuggestionComment"> | string
}

export type SuggestionCommentCreateWithoutCreatedByInput = {
  id?: string
  comment: string
  isAnonymous?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  suggestion: Prisma.SuggestionCreateNestedOneWithoutCommentsInput
}

export type SuggestionCommentUncheckedCreateWithoutCreatedByInput = {
  id?: string
  comment: string
  isAnonymous?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  suggestionId: string
}

export type SuggestionCommentCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.SuggestionCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutCreatedByInput, Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput>
}

export type SuggestionCommentCreateManyCreatedByInputEnvelope = {
  data: Prisma.SuggestionCommentCreateManyCreatedByInput | Prisma.SuggestionCommentCreateManyCreatedByInput[]
  skipDuplicates?: boolean
}

export type SuggestionCommentUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.SuggestionCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.SuggestionCommentUpdateWithoutCreatedByInput, Prisma.SuggestionCommentUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.SuggestionCommentCreateWithoutCreatedByInput, Prisma.SuggestionCommentUncheckedCreateWithoutCreatedByInput>
}

export type SuggestionCommentUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.SuggestionCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.SuggestionCommentUpdateWithoutCreatedByInput, Prisma.SuggestionCommentUncheckedUpdateWithoutCreatedByInput>
}

export type SuggestionCommentUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.SuggestionCommentScalarWhereInput
  data: Prisma.XOR<Prisma.SuggestionCommentUpdateManyMutationInput, Prisma.SuggestionCommentUncheckedUpdateManyWithoutCreatedByInput>
}

export type SuggestionCommentCreateManySuggestionInput = {
  id?: string
  comment: string
  isAnonymous?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
}

export type SuggestionCommentUpdateWithoutSuggestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdBy?: Prisma.UserUpdateOneRequiredWithoutSuggestionCommentNestedInput
}

export type SuggestionCommentUncheckedUpdateWithoutSuggestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionCommentUncheckedUpdateManyWithoutSuggestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionCommentCreateManyCreatedByInput = {
  id?: string
  comment: string
  isAnonymous?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  suggestionId: string
}

export type SuggestionCommentUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  suggestion?: Prisma.SuggestionUpdateOneRequiredWithoutCommentsNestedInput
}

export type SuggestionCommentUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  suggestionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SuggestionCommentUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  comment?: Prisma.StringFieldUpdateOperationsInput | string
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  suggestionId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SuggestionCommentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  comment?: boolean
  isAnonymous?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  suggestionId?: boolean
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["suggestionComment"]>

export type SuggestionCommentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  comment?: boolean
  isAnonymous?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  suggestionId?: boolean
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["suggestionComment"]>

export type SuggestionCommentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  comment?: boolean
  isAnonymous?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  suggestionId?: boolean
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["suggestionComment"]>

export type SuggestionCommentSelectScalar = {
  id?: boolean
  comment?: boolean
  isAnonymous?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  createdById?: boolean
  suggestionId?: boolean
}

export type SuggestionCommentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "comment" | "isAnonymous" | "createdAt" | "updatedAt" | "createdById" | "suggestionId", ExtArgs["result"]["suggestionComment"]>
export type SuggestionCommentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}
export type SuggestionCommentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}
export type SuggestionCommentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  suggestion?: boolean | Prisma.SuggestionDefaultArgs<ExtArgs>
}

export type $SuggestionCommentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SuggestionComment"
  objects: {
    createdBy: Prisma.$UserPayload<ExtArgs>
    suggestion: Prisma.$SuggestionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    comment: string
    isAnonymous: boolean
    createdAt: Date
    updatedAt: Date
    createdById: string
    suggestionId: string
  }, ExtArgs["result"]["suggestionComment"]>
  composites: {}
}

export type SuggestionCommentGetPayload<S extends boolean | null | undefined | SuggestionCommentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload, S>

export type SuggestionCommentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SuggestionCommentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SuggestionCommentCountAggregateInputType | true
  }

export interface SuggestionCommentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SuggestionComment'], meta: { name: 'SuggestionComment' } }
  /**
   * Find zero or one SuggestionComment that matches the filter.
   * @param {SuggestionCommentFindUniqueArgs} args - Arguments to find a SuggestionComment
   * @example
   * // Get one SuggestionComment
   * const suggestionComment = await prisma.suggestionComment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SuggestionCommentFindUniqueArgs>(args: Prisma.SelectSubset<T, SuggestionCommentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SuggestionCommentClient<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SuggestionComment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SuggestionCommentFindUniqueOrThrowArgs} args - Arguments to find a SuggestionComment
   * @example
   * // Get one SuggestionComment
   * const suggestionComment = await prisma.suggestionComment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SuggestionCommentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SuggestionCommentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SuggestionCommentClient<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SuggestionComment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionCommentFindFirstArgs} args - Arguments to find a SuggestionComment
   * @example
   * // Get one SuggestionComment
   * const suggestionComment = await prisma.suggestionComment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SuggestionCommentFindFirstArgs>(args?: Prisma.SelectSubset<T, SuggestionCommentFindFirstArgs<ExtArgs>>): Prisma.Prisma__SuggestionCommentClient<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SuggestionComment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionCommentFindFirstOrThrowArgs} args - Arguments to find a SuggestionComment
   * @example
   * // Get one SuggestionComment
   * const suggestionComment = await prisma.suggestionComment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SuggestionCommentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SuggestionCommentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SuggestionCommentClient<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SuggestionComments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionCommentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SuggestionComments
   * const suggestionComments = await prisma.suggestionComment.findMany()
   * 
   * // Get first 10 SuggestionComments
   * const suggestionComments = await prisma.suggestionComment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const suggestionCommentWithIdOnly = await prisma.suggestionComment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SuggestionCommentFindManyArgs>(args?: Prisma.SelectSubset<T, SuggestionCommentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SuggestionComment.
   * @param {SuggestionCommentCreateArgs} args - Arguments to create a SuggestionComment.
   * @example
   * // Create one SuggestionComment
   * const SuggestionComment = await prisma.suggestionComment.create({
   *   data: {
   *     // ... data to create a SuggestionComment
   *   }
   * })
   * 
   */
  create<T extends SuggestionCommentCreateArgs>(args: Prisma.SelectSubset<T, SuggestionCommentCreateArgs<ExtArgs>>): Prisma.Prisma__SuggestionCommentClient<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SuggestionComments.
   * @param {SuggestionCommentCreateManyArgs} args - Arguments to create many SuggestionComments.
   * @example
   * // Create many SuggestionComments
   * const suggestionComment = await prisma.suggestionComment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SuggestionCommentCreateManyArgs>(args?: Prisma.SelectSubset<T, SuggestionCommentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SuggestionComments and returns the data saved in the database.
   * @param {SuggestionCommentCreateManyAndReturnArgs} args - Arguments to create many SuggestionComments.
   * @example
   * // Create many SuggestionComments
   * const suggestionComment = await prisma.suggestionComment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SuggestionComments and only return the `id`
   * const suggestionCommentWithIdOnly = await prisma.suggestionComment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SuggestionCommentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SuggestionCommentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SuggestionComment.
   * @param {SuggestionCommentDeleteArgs} args - Arguments to delete one SuggestionComment.
   * @example
   * // Delete one SuggestionComment
   * const SuggestionComment = await prisma.suggestionComment.delete({
   *   where: {
   *     // ... filter to delete one SuggestionComment
   *   }
   * })
   * 
   */
  delete<T extends SuggestionCommentDeleteArgs>(args: Prisma.SelectSubset<T, SuggestionCommentDeleteArgs<ExtArgs>>): Prisma.Prisma__SuggestionCommentClient<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SuggestionComment.
   * @param {SuggestionCommentUpdateArgs} args - Arguments to update one SuggestionComment.
   * @example
   * // Update one SuggestionComment
   * const suggestionComment = await prisma.suggestionComment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SuggestionCommentUpdateArgs>(args: Prisma.SelectSubset<T, SuggestionCommentUpdateArgs<ExtArgs>>): Prisma.Prisma__SuggestionCommentClient<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SuggestionComments.
   * @param {SuggestionCommentDeleteManyArgs} args - Arguments to filter SuggestionComments to delete.
   * @example
   * // Delete a few SuggestionComments
   * const { count } = await prisma.suggestionComment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SuggestionCommentDeleteManyArgs>(args?: Prisma.SelectSubset<T, SuggestionCommentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SuggestionComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionCommentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SuggestionComments
   * const suggestionComment = await prisma.suggestionComment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SuggestionCommentUpdateManyArgs>(args: Prisma.SelectSubset<T, SuggestionCommentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SuggestionComments and returns the data updated in the database.
   * @param {SuggestionCommentUpdateManyAndReturnArgs} args - Arguments to update many SuggestionComments.
   * @example
   * // Update many SuggestionComments
   * const suggestionComment = await prisma.suggestionComment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SuggestionComments and only return the `id`
   * const suggestionCommentWithIdOnly = await prisma.suggestionComment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SuggestionCommentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SuggestionCommentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SuggestionComment.
   * @param {SuggestionCommentUpsertArgs} args - Arguments to update or create a SuggestionComment.
   * @example
   * // Update or create a SuggestionComment
   * const suggestionComment = await prisma.suggestionComment.upsert({
   *   create: {
   *     // ... data to create a SuggestionComment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SuggestionComment we want to update
   *   }
   * })
   */
  upsert<T extends SuggestionCommentUpsertArgs>(args: Prisma.SelectSubset<T, SuggestionCommentUpsertArgs<ExtArgs>>): Prisma.Prisma__SuggestionCommentClient<runtime.Types.Result.GetResult<Prisma.$SuggestionCommentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SuggestionComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionCommentCountArgs} args - Arguments to filter SuggestionComments to count.
   * @example
   * // Count the number of SuggestionComments
   * const count = await prisma.suggestionComment.count({
   *   where: {
   *     // ... the filter for the SuggestionComments we want to count
   *   }
   * })
  **/
  count<T extends SuggestionCommentCountArgs>(
    args?: Prisma.Subset<T, SuggestionCommentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SuggestionCommentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SuggestionComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionCommentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SuggestionCommentAggregateArgs>(args: Prisma.Subset<T, SuggestionCommentAggregateArgs>): Prisma.PrismaPromise<GetSuggestionCommentAggregateType<T>>

  /**
   * Group by SuggestionComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SuggestionCommentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SuggestionCommentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SuggestionCommentGroupByArgs['orderBy'] }
      : { orderBy?: SuggestionCommentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SuggestionCommentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSuggestionCommentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SuggestionComment model
 */
readonly fields: SuggestionCommentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SuggestionComment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SuggestionCommentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  createdBy<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  suggestion<T extends Prisma.SuggestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SuggestionDefaultArgs<ExtArgs>>): Prisma.Prisma__SuggestionClient<runtime.Types.Result.GetResult<Prisma.$SuggestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SuggestionComment model
 */
export interface SuggestionCommentFieldRefs {
  readonly id: Prisma.FieldRef<"SuggestionComment", 'String'>
  readonly comment: Prisma.FieldRef<"SuggestionComment", 'String'>
  readonly isAnonymous: Prisma.FieldRef<"SuggestionComment", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"SuggestionComment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SuggestionComment", 'DateTime'>
  readonly createdById: Prisma.FieldRef<"SuggestionComment", 'String'>
  readonly suggestionId: Prisma.FieldRef<"SuggestionComment", 'String'>
}
    

// Custom InputTypes
/**
 * SuggestionComment findUnique
 */
export type SuggestionCommentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionComment to fetch.
   */
  where: Prisma.SuggestionCommentWhereUniqueInput
}

/**
 * SuggestionComment findUniqueOrThrow
 */
export type SuggestionCommentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionComment to fetch.
   */
  where: Prisma.SuggestionCommentWhereUniqueInput
}

/**
 * SuggestionComment findFirst
 */
export type SuggestionCommentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionComment to fetch.
   */
  where?: Prisma.SuggestionCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SuggestionComments to fetch.
   */
  orderBy?: Prisma.SuggestionCommentOrderByWithRelationInput | Prisma.SuggestionCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SuggestionComments.
   */
  cursor?: Prisma.SuggestionCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SuggestionComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SuggestionComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SuggestionComments.
   */
  distinct?: Prisma.SuggestionCommentScalarFieldEnum | Prisma.SuggestionCommentScalarFieldEnum[]
}

/**
 * SuggestionComment findFirstOrThrow
 */
export type SuggestionCommentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionComment to fetch.
   */
  where?: Prisma.SuggestionCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SuggestionComments to fetch.
   */
  orderBy?: Prisma.SuggestionCommentOrderByWithRelationInput | Prisma.SuggestionCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SuggestionComments.
   */
  cursor?: Prisma.SuggestionCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SuggestionComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SuggestionComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SuggestionComments.
   */
  distinct?: Prisma.SuggestionCommentScalarFieldEnum | Prisma.SuggestionCommentScalarFieldEnum[]
}

/**
 * SuggestionComment findMany
 */
export type SuggestionCommentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
  /**
   * Filter, which SuggestionComments to fetch.
   */
  where?: Prisma.SuggestionCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SuggestionComments to fetch.
   */
  orderBy?: Prisma.SuggestionCommentOrderByWithRelationInput | Prisma.SuggestionCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SuggestionComments.
   */
  cursor?: Prisma.SuggestionCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SuggestionComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SuggestionComments.
   */
  skip?: number
  distinct?: Prisma.SuggestionCommentScalarFieldEnum | Prisma.SuggestionCommentScalarFieldEnum[]
}

/**
 * SuggestionComment create
 */
export type SuggestionCommentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
  /**
   * The data needed to create a SuggestionComment.
   */
  data: Prisma.XOR<Prisma.SuggestionCommentCreateInput, Prisma.SuggestionCommentUncheckedCreateInput>
}

/**
 * SuggestionComment createMany
 */
export type SuggestionCommentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SuggestionComments.
   */
  data: Prisma.SuggestionCommentCreateManyInput | Prisma.SuggestionCommentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SuggestionComment createManyAndReturn
 */
export type SuggestionCommentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * The data used to create many SuggestionComments.
   */
  data: Prisma.SuggestionCommentCreateManyInput | Prisma.SuggestionCommentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SuggestionComment update
 */
export type SuggestionCommentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
  /**
   * The data needed to update a SuggestionComment.
   */
  data: Prisma.XOR<Prisma.SuggestionCommentUpdateInput, Prisma.SuggestionCommentUncheckedUpdateInput>
  /**
   * Choose, which SuggestionComment to update.
   */
  where: Prisma.SuggestionCommentWhereUniqueInput
}

/**
 * SuggestionComment updateMany
 */
export type SuggestionCommentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SuggestionComments.
   */
  data: Prisma.XOR<Prisma.SuggestionCommentUpdateManyMutationInput, Prisma.SuggestionCommentUncheckedUpdateManyInput>
  /**
   * Filter which SuggestionComments to update
   */
  where?: Prisma.SuggestionCommentWhereInput
  /**
   * Limit how many SuggestionComments to update.
   */
  limit?: number
}

/**
 * SuggestionComment updateManyAndReturn
 */
export type SuggestionCommentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * The data used to update SuggestionComments.
   */
  data: Prisma.XOR<Prisma.SuggestionCommentUpdateManyMutationInput, Prisma.SuggestionCommentUncheckedUpdateManyInput>
  /**
   * Filter which SuggestionComments to update
   */
  where?: Prisma.SuggestionCommentWhereInput
  /**
   * Limit how many SuggestionComments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SuggestionComment upsert
 */
export type SuggestionCommentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
  /**
   * The filter to search for the SuggestionComment to update in case it exists.
   */
  where: Prisma.SuggestionCommentWhereUniqueInput
  /**
   * In case the SuggestionComment found by the `where` argument doesn't exist, create a new SuggestionComment with this data.
   */
  create: Prisma.XOR<Prisma.SuggestionCommentCreateInput, Prisma.SuggestionCommentUncheckedCreateInput>
  /**
   * In case the SuggestionComment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SuggestionCommentUpdateInput, Prisma.SuggestionCommentUncheckedUpdateInput>
}

/**
 * SuggestionComment delete
 */
export type SuggestionCommentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
  /**
   * Filter which SuggestionComment to delete.
   */
  where: Prisma.SuggestionCommentWhereUniqueInput
}

/**
 * SuggestionComment deleteMany
 */
export type SuggestionCommentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SuggestionComments to delete
   */
  where?: Prisma.SuggestionCommentWhereInput
  /**
   * Limit how many SuggestionComments to delete.
   */
  limit?: number
}

/**
 * SuggestionComment without action
 */
export type SuggestionCommentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SuggestionComment
   */
  select?: Prisma.SuggestionCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SuggestionComment
   */
  omit?: Prisma.SuggestionCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SuggestionCommentInclude<ExtArgs> | null
}
