
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `UserStudent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UserStudent
 * 
 */
export type UserStudentModel = runtime.Types.Result.DefaultSelection<Prisma.$UserStudentPayload>

export type AggregateUserStudent = {
  _count: UserStudentCountAggregateOutputType | null
  _min: UserStudentMinAggregateOutputType | null
  _max: UserStudentMaxAggregateOutputType | null
}

export type UserStudentMinAggregateOutputType = {
  id: string | null
  userId: string | null
  studentId: string | null
  groupId: string | null
  relation: string | null
}

export type UserStudentMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  studentId: string | null
  groupId: string | null
  relation: string | null
}

export type UserStudentCountAggregateOutputType = {
  id: number
  userId: number
  studentId: number
  groupId: number
  relation: number
  _all: number
}


export type UserStudentMinAggregateInputType = {
  id?: true
  userId?: true
  studentId?: true
  groupId?: true
  relation?: true
}

export type UserStudentMaxAggregateInputType = {
  id?: true
  userId?: true
  studentId?: true
  groupId?: true
  relation?: true
}

export type UserStudentCountAggregateInputType = {
  id?: true
  userId?: true
  studentId?: true
  groupId?: true
  relation?: true
  _all?: true
}

export type UserStudentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserStudent to aggregate.
   */
  where?: Prisma.UserStudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserStudents to fetch.
   */
  orderBy?: Prisma.UserStudentOrderByWithRelationInput | Prisma.UserStudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserStudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserStudents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserStudents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserStudents
  **/
  _count?: true | UserStudentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserStudentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserStudentMaxAggregateInputType
}

export type GetUserStudentAggregateType<T extends UserStudentAggregateArgs> = {
      [P in keyof T & keyof AggregateUserStudent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserStudent[P]>
    : Prisma.GetScalarType<T[P], AggregateUserStudent[P]>
}




export type UserStudentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserStudentWhereInput
  orderBy?: Prisma.UserStudentOrderByWithAggregationInput | Prisma.UserStudentOrderByWithAggregationInput[]
  by: Prisma.UserStudentScalarFieldEnum[] | Prisma.UserStudentScalarFieldEnum
  having?: Prisma.UserStudentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserStudentCountAggregateInputType | true
  _min?: UserStudentMinAggregateInputType
  _max?: UserStudentMaxAggregateInputType
}

export type UserStudentGroupByOutputType = {
  id: string
  userId: string
  studentId: string
  groupId: string
  relation: string
  _count: UserStudentCountAggregateOutputType | null
  _min: UserStudentMinAggregateOutputType | null
  _max: UserStudentMaxAggregateOutputType | null
}

type GetUserStudentGroupByPayload<T extends UserStudentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserStudentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserStudentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserStudentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserStudentGroupByOutputType[P]>
      }
    >
  > 



export type UserStudentWhereInput = {
  AND?: Prisma.UserStudentWhereInput | Prisma.UserStudentWhereInput[]
  OR?: Prisma.UserStudentWhereInput[]
  NOT?: Prisma.UserStudentWhereInput | Prisma.UserStudentWhereInput[]
  id?: Prisma.StringFilter<"UserStudent"> | string
  userId?: Prisma.StringFilter<"UserStudent"> | string
  studentId?: Prisma.StringFilter<"UserStudent"> | string
  groupId?: Prisma.StringFilter<"UserStudent"> | string
  relation?: Prisma.StringFilter<"UserStudent"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  group?: Prisma.XOR<Prisma.GroupScalarRelationFilter, Prisma.GroupWhereInput>
}

export type UserStudentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  relation?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  student?: Prisma.StudentOrderByWithRelationInput
  group?: Prisma.GroupOrderByWithRelationInput
  _relevance?: Prisma.UserStudentOrderByRelevanceInput
}

export type UserStudentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_studentId?: Prisma.UserStudentUserIdStudentIdCompoundUniqueInput
  AND?: Prisma.UserStudentWhereInput | Prisma.UserStudentWhereInput[]
  OR?: Prisma.UserStudentWhereInput[]
  NOT?: Prisma.UserStudentWhereInput | Prisma.UserStudentWhereInput[]
  userId?: Prisma.StringFilter<"UserStudent"> | string
  studentId?: Prisma.StringFilter<"UserStudent"> | string
  groupId?: Prisma.StringFilter<"UserStudent"> | string
  relation?: Prisma.StringFilter<"UserStudent"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  student?: Prisma.XOR<Prisma.StudentScalarRelationFilter, Prisma.StudentWhereInput>
  group?: Prisma.XOR<Prisma.GroupScalarRelationFilter, Prisma.GroupWhereInput>
}, "id" | "userId_studentId">

export type UserStudentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  relation?: Prisma.SortOrder
  _count?: Prisma.UserStudentCountOrderByAggregateInput
  _max?: Prisma.UserStudentMaxOrderByAggregateInput
  _min?: Prisma.UserStudentMinOrderByAggregateInput
}

export type UserStudentScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserStudentScalarWhereWithAggregatesInput | Prisma.UserStudentScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserStudentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserStudentScalarWhereWithAggregatesInput | Prisma.UserStudentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserStudent"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserStudent"> | string
  studentId?: Prisma.StringWithAggregatesFilter<"UserStudent"> | string
  groupId?: Prisma.StringWithAggregatesFilter<"UserStudent"> | string
  relation?: Prisma.StringWithAggregatesFilter<"UserStudent"> | string
}

export type UserStudentCreateInput = {
  id?: string
  relation: string
  user: Prisma.UserCreateNestedOneWithoutStudentsInput
  student: Prisma.StudentCreateNestedOneWithoutParentsInput
  group: Prisma.GroupCreateNestedOneWithoutUserStudentInput
}

export type UserStudentUncheckedCreateInput = {
  id?: string
  userId: string
  studentId: string
  groupId: string
  relation: string
}

export type UserStudentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutStudentsNestedInput
  student?: Prisma.StudentUpdateOneRequiredWithoutParentsNestedInput
  group?: Prisma.GroupUpdateOneRequiredWithoutUserStudentNestedInput
}

export type UserStudentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStudentCreateManyInput = {
  id?: string
  userId: string
  studentId: string
  groupId: string
  relation: string
}

export type UserStudentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStudentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStudentListRelationFilter = {
  every?: Prisma.UserStudentWhereInput
  some?: Prisma.UserStudentWhereInput
  none?: Prisma.UserStudentWhereInput
}

export type UserStudentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserStudentOrderByRelevanceInput = {
  fields: Prisma.UserStudentOrderByRelevanceFieldEnum | Prisma.UserStudentOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type UserStudentUserIdStudentIdCompoundUniqueInput = {
  userId: string
  studentId: string
}

export type UserStudentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  relation?: Prisma.SortOrder
}

export type UserStudentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  relation?: Prisma.SortOrder
}

export type UserStudentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  relation?: Prisma.SortOrder
}

export type UserStudentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutUserInput, Prisma.UserStudentUncheckedCreateWithoutUserInput> | Prisma.UserStudentCreateWithoutUserInput[] | Prisma.UserStudentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutUserInput | Prisma.UserStudentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserStudentCreateManyUserInputEnvelope
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
}

export type UserStudentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutUserInput, Prisma.UserStudentUncheckedCreateWithoutUserInput> | Prisma.UserStudentCreateWithoutUserInput[] | Prisma.UserStudentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutUserInput | Prisma.UserStudentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserStudentCreateManyUserInputEnvelope
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
}

export type UserStudentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutUserInput, Prisma.UserStudentUncheckedCreateWithoutUserInput> | Prisma.UserStudentCreateWithoutUserInput[] | Prisma.UserStudentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutUserInput | Prisma.UserStudentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserStudentUpsertWithWhereUniqueWithoutUserInput | Prisma.UserStudentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserStudentCreateManyUserInputEnvelope
  set?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  disconnect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  delete?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  update?: Prisma.UserStudentUpdateWithWhereUniqueWithoutUserInput | Prisma.UserStudentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserStudentUpdateManyWithWhereWithoutUserInput | Prisma.UserStudentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserStudentScalarWhereInput | Prisma.UserStudentScalarWhereInput[]
}

export type UserStudentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutUserInput, Prisma.UserStudentUncheckedCreateWithoutUserInput> | Prisma.UserStudentCreateWithoutUserInput[] | Prisma.UserStudentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutUserInput | Prisma.UserStudentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserStudentUpsertWithWhereUniqueWithoutUserInput | Prisma.UserStudentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserStudentCreateManyUserInputEnvelope
  set?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  disconnect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  delete?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  update?: Prisma.UserStudentUpdateWithWhereUniqueWithoutUserInput | Prisma.UserStudentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserStudentUpdateManyWithWhereWithoutUserInput | Prisma.UserStudentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserStudentScalarWhereInput | Prisma.UserStudentScalarWhereInput[]
}

export type UserStudentCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutStudentInput, Prisma.UserStudentUncheckedCreateWithoutStudentInput> | Prisma.UserStudentCreateWithoutStudentInput[] | Prisma.UserStudentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutStudentInput | Prisma.UserStudentCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.UserStudentCreateManyStudentInputEnvelope
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
}

export type UserStudentUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutStudentInput, Prisma.UserStudentUncheckedCreateWithoutStudentInput> | Prisma.UserStudentCreateWithoutStudentInput[] | Prisma.UserStudentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutStudentInput | Prisma.UserStudentCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.UserStudentCreateManyStudentInputEnvelope
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
}

export type UserStudentUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutStudentInput, Prisma.UserStudentUncheckedCreateWithoutStudentInput> | Prisma.UserStudentCreateWithoutStudentInput[] | Prisma.UserStudentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutStudentInput | Prisma.UserStudentCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.UserStudentUpsertWithWhereUniqueWithoutStudentInput | Prisma.UserStudentUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.UserStudentCreateManyStudentInputEnvelope
  set?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  disconnect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  delete?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  update?: Prisma.UserStudentUpdateWithWhereUniqueWithoutStudentInput | Prisma.UserStudentUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.UserStudentUpdateManyWithWhereWithoutStudentInput | Prisma.UserStudentUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.UserStudentScalarWhereInput | Prisma.UserStudentScalarWhereInput[]
}

export type UserStudentUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutStudentInput, Prisma.UserStudentUncheckedCreateWithoutStudentInput> | Prisma.UserStudentCreateWithoutStudentInput[] | Prisma.UserStudentUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutStudentInput | Prisma.UserStudentCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.UserStudentUpsertWithWhereUniqueWithoutStudentInput | Prisma.UserStudentUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.UserStudentCreateManyStudentInputEnvelope
  set?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  disconnect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  delete?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  update?: Prisma.UserStudentUpdateWithWhereUniqueWithoutStudentInput | Prisma.UserStudentUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.UserStudentUpdateManyWithWhereWithoutStudentInput | Prisma.UserStudentUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.UserStudentScalarWhereInput | Prisma.UserStudentScalarWhereInput[]
}

export type UserStudentCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutGroupInput, Prisma.UserStudentUncheckedCreateWithoutGroupInput> | Prisma.UserStudentCreateWithoutGroupInput[] | Prisma.UserStudentUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutGroupInput | Prisma.UserStudentCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.UserStudentCreateManyGroupInputEnvelope
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
}

export type UserStudentUncheckedCreateNestedManyWithoutGroupInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutGroupInput, Prisma.UserStudentUncheckedCreateWithoutGroupInput> | Prisma.UserStudentCreateWithoutGroupInput[] | Prisma.UserStudentUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutGroupInput | Prisma.UserStudentCreateOrConnectWithoutGroupInput[]
  createMany?: Prisma.UserStudentCreateManyGroupInputEnvelope
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
}

export type UserStudentUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutGroupInput, Prisma.UserStudentUncheckedCreateWithoutGroupInput> | Prisma.UserStudentCreateWithoutGroupInput[] | Prisma.UserStudentUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutGroupInput | Prisma.UserStudentCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.UserStudentUpsertWithWhereUniqueWithoutGroupInput | Prisma.UserStudentUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.UserStudentCreateManyGroupInputEnvelope
  set?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  disconnect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  delete?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  update?: Prisma.UserStudentUpdateWithWhereUniqueWithoutGroupInput | Prisma.UserStudentUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.UserStudentUpdateManyWithWhereWithoutGroupInput | Prisma.UserStudentUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.UserStudentScalarWhereInput | Prisma.UserStudentScalarWhereInput[]
}

export type UserStudentUncheckedUpdateManyWithoutGroupNestedInput = {
  create?: Prisma.XOR<Prisma.UserStudentCreateWithoutGroupInput, Prisma.UserStudentUncheckedCreateWithoutGroupInput> | Prisma.UserStudentCreateWithoutGroupInput[] | Prisma.UserStudentUncheckedCreateWithoutGroupInput[]
  connectOrCreate?: Prisma.UserStudentCreateOrConnectWithoutGroupInput | Prisma.UserStudentCreateOrConnectWithoutGroupInput[]
  upsert?: Prisma.UserStudentUpsertWithWhereUniqueWithoutGroupInput | Prisma.UserStudentUpsertWithWhereUniqueWithoutGroupInput[]
  createMany?: Prisma.UserStudentCreateManyGroupInputEnvelope
  set?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  disconnect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  delete?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  connect?: Prisma.UserStudentWhereUniqueInput | Prisma.UserStudentWhereUniqueInput[]
  update?: Prisma.UserStudentUpdateWithWhereUniqueWithoutGroupInput | Prisma.UserStudentUpdateWithWhereUniqueWithoutGroupInput[]
  updateMany?: Prisma.UserStudentUpdateManyWithWhereWithoutGroupInput | Prisma.UserStudentUpdateManyWithWhereWithoutGroupInput[]
  deleteMany?: Prisma.UserStudentScalarWhereInput | Prisma.UserStudentScalarWhereInput[]
}

export type UserStudentCreateWithoutUserInput = {
  id?: string
  relation: string
  student: Prisma.StudentCreateNestedOneWithoutParentsInput
  group: Prisma.GroupCreateNestedOneWithoutUserStudentInput
}

export type UserStudentUncheckedCreateWithoutUserInput = {
  id?: string
  studentId: string
  groupId: string
  relation: string
}

export type UserStudentCreateOrConnectWithoutUserInput = {
  where: Prisma.UserStudentWhereUniqueInput
  create: Prisma.XOR<Prisma.UserStudentCreateWithoutUserInput, Prisma.UserStudentUncheckedCreateWithoutUserInput>
}

export type UserStudentCreateManyUserInputEnvelope = {
  data: Prisma.UserStudentCreateManyUserInput | Prisma.UserStudentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserStudentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserStudentWhereUniqueInput
  update: Prisma.XOR<Prisma.UserStudentUpdateWithoutUserInput, Prisma.UserStudentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserStudentCreateWithoutUserInput, Prisma.UserStudentUncheckedCreateWithoutUserInput>
}

export type UserStudentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserStudentWhereUniqueInput
  data: Prisma.XOR<Prisma.UserStudentUpdateWithoutUserInput, Prisma.UserStudentUncheckedUpdateWithoutUserInput>
}

export type UserStudentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserStudentScalarWhereInput
  data: Prisma.XOR<Prisma.UserStudentUpdateManyMutationInput, Prisma.UserStudentUncheckedUpdateManyWithoutUserInput>
}

export type UserStudentScalarWhereInput = {
  AND?: Prisma.UserStudentScalarWhereInput | Prisma.UserStudentScalarWhereInput[]
  OR?: Prisma.UserStudentScalarWhereInput[]
  NOT?: Prisma.UserStudentScalarWhereInput | Prisma.UserStudentScalarWhereInput[]
  id?: Prisma.StringFilter<"UserStudent"> | string
  userId?: Prisma.StringFilter<"UserStudent"> | string
  studentId?: Prisma.StringFilter<"UserStudent"> | string
  groupId?: Prisma.StringFilter<"UserStudent"> | string
  relation?: Prisma.StringFilter<"UserStudent"> | string
}

export type UserStudentCreateWithoutStudentInput = {
  id?: string
  relation: string
  user: Prisma.UserCreateNestedOneWithoutStudentsInput
  group: Prisma.GroupCreateNestedOneWithoutUserStudentInput
}

export type UserStudentUncheckedCreateWithoutStudentInput = {
  id?: string
  userId: string
  groupId: string
  relation: string
}

export type UserStudentCreateOrConnectWithoutStudentInput = {
  where: Prisma.UserStudentWhereUniqueInput
  create: Prisma.XOR<Prisma.UserStudentCreateWithoutStudentInput, Prisma.UserStudentUncheckedCreateWithoutStudentInput>
}

export type UserStudentCreateManyStudentInputEnvelope = {
  data: Prisma.UserStudentCreateManyStudentInput | Prisma.UserStudentCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type UserStudentUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.UserStudentWhereUniqueInput
  update: Prisma.XOR<Prisma.UserStudentUpdateWithoutStudentInput, Prisma.UserStudentUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.UserStudentCreateWithoutStudentInput, Prisma.UserStudentUncheckedCreateWithoutStudentInput>
}

export type UserStudentUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.UserStudentWhereUniqueInput
  data: Prisma.XOR<Prisma.UserStudentUpdateWithoutStudentInput, Prisma.UserStudentUncheckedUpdateWithoutStudentInput>
}

export type UserStudentUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.UserStudentScalarWhereInput
  data: Prisma.XOR<Prisma.UserStudentUpdateManyMutationInput, Prisma.UserStudentUncheckedUpdateManyWithoutStudentInput>
}

export type UserStudentCreateWithoutGroupInput = {
  id?: string
  relation: string
  user: Prisma.UserCreateNestedOneWithoutStudentsInput
  student: Prisma.StudentCreateNestedOneWithoutParentsInput
}

export type UserStudentUncheckedCreateWithoutGroupInput = {
  id?: string
  userId: string
  studentId: string
  relation: string
}

export type UserStudentCreateOrConnectWithoutGroupInput = {
  where: Prisma.UserStudentWhereUniqueInput
  create: Prisma.XOR<Prisma.UserStudentCreateWithoutGroupInput, Prisma.UserStudentUncheckedCreateWithoutGroupInput>
}

export type UserStudentCreateManyGroupInputEnvelope = {
  data: Prisma.UserStudentCreateManyGroupInput | Prisma.UserStudentCreateManyGroupInput[]
  skipDuplicates?: boolean
}

export type UserStudentUpsertWithWhereUniqueWithoutGroupInput = {
  where: Prisma.UserStudentWhereUniqueInput
  update: Prisma.XOR<Prisma.UserStudentUpdateWithoutGroupInput, Prisma.UserStudentUncheckedUpdateWithoutGroupInput>
  create: Prisma.XOR<Prisma.UserStudentCreateWithoutGroupInput, Prisma.UserStudentUncheckedCreateWithoutGroupInput>
}

export type UserStudentUpdateWithWhereUniqueWithoutGroupInput = {
  where: Prisma.UserStudentWhereUniqueInput
  data: Prisma.XOR<Prisma.UserStudentUpdateWithoutGroupInput, Prisma.UserStudentUncheckedUpdateWithoutGroupInput>
}

export type UserStudentUpdateManyWithWhereWithoutGroupInput = {
  where: Prisma.UserStudentScalarWhereInput
  data: Prisma.XOR<Prisma.UserStudentUpdateManyMutationInput, Prisma.UserStudentUncheckedUpdateManyWithoutGroupInput>
}

export type UserStudentCreateManyUserInput = {
  id?: string
  studentId: string
  groupId: string
  relation: string
}

export type UserStudentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
  student?: Prisma.StudentUpdateOneRequiredWithoutParentsNestedInput
  group?: Prisma.GroupUpdateOneRequiredWithoutUserStudentNestedInput
}

export type UserStudentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStudentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStudentCreateManyStudentInput = {
  id?: string
  userId: string
  groupId: string
  relation: string
}

export type UserStudentUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutStudentsNestedInput
  group?: Prisma.GroupUpdateOneRequiredWithoutUserStudentNestedInput
}

export type UserStudentUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStudentUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStudentCreateManyGroupInput = {
  id?: string
  userId: string
  studentId: string
  relation: string
}

export type UserStudentUpdateWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutStudentsNestedInput
  student?: Prisma.StudentUpdateOneRequiredWithoutParentsNestedInput
}

export type UserStudentUncheckedUpdateWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserStudentUncheckedUpdateManyWithoutGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  relation?: Prisma.StringFieldUpdateOperationsInput | string
}



export type UserStudentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  studentId?: boolean
  groupId?: boolean
  relation?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userStudent"]>

export type UserStudentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  studentId?: boolean
  groupId?: boolean
  relation?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userStudent"]>

export type UserStudentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  studentId?: boolean
  groupId?: boolean
  relation?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userStudent"]>

export type UserStudentSelectScalar = {
  id?: boolean
  userId?: boolean
  studentId?: boolean
  groupId?: boolean
  relation?: boolean
}

export type UserStudentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "studentId" | "groupId" | "relation", ExtArgs["result"]["userStudent"]>
export type UserStudentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}
export type UserStudentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}
export type UserStudentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  student?: boolean | Prisma.StudentDefaultArgs<ExtArgs>
  group?: boolean | Prisma.GroupDefaultArgs<ExtArgs>
}

export type $UserStudentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserStudent"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    student: Prisma.$StudentPayload<ExtArgs>
    group: Prisma.$GroupPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    studentId: string
    groupId: string
    relation: string
  }, ExtArgs["result"]["userStudent"]>
  composites: {}
}

export type UserStudentGetPayload<S extends boolean | null | undefined | UserStudentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserStudentPayload, S>

export type UserStudentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserStudentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserStudentCountAggregateInputType | true
  }

export interface UserStudentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserStudent'], meta: { name: 'UserStudent' } }
  /**
   * Find zero or one UserStudent that matches the filter.
   * @param {UserStudentFindUniqueArgs} args - Arguments to find a UserStudent
   * @example
   * // Get one UserStudent
   * const userStudent = await prisma.userStudent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserStudentFindUniqueArgs>(args: Prisma.SelectSubset<T, UserStudentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserStudentClient<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserStudent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserStudentFindUniqueOrThrowArgs} args - Arguments to find a UserStudent
   * @example
   * // Get one UserStudent
   * const userStudent = await prisma.userStudent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserStudentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserStudentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserStudentClient<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserStudent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStudentFindFirstArgs} args - Arguments to find a UserStudent
   * @example
   * // Get one UserStudent
   * const userStudent = await prisma.userStudent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserStudentFindFirstArgs>(args?: Prisma.SelectSubset<T, UserStudentFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserStudentClient<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserStudent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStudentFindFirstOrThrowArgs} args - Arguments to find a UserStudent
   * @example
   * // Get one UserStudent
   * const userStudent = await prisma.userStudent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserStudentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserStudentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserStudentClient<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserStudents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStudentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserStudents
   * const userStudents = await prisma.userStudent.findMany()
   * 
   * // Get first 10 UserStudents
   * const userStudents = await prisma.userStudent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userStudentWithIdOnly = await prisma.userStudent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserStudentFindManyArgs>(args?: Prisma.SelectSubset<T, UserStudentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserStudent.
   * @param {UserStudentCreateArgs} args - Arguments to create a UserStudent.
   * @example
   * // Create one UserStudent
   * const UserStudent = await prisma.userStudent.create({
   *   data: {
   *     // ... data to create a UserStudent
   *   }
   * })
   * 
   */
  create<T extends UserStudentCreateArgs>(args: Prisma.SelectSubset<T, UserStudentCreateArgs<ExtArgs>>): Prisma.Prisma__UserStudentClient<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserStudents.
   * @param {UserStudentCreateManyArgs} args - Arguments to create many UserStudents.
   * @example
   * // Create many UserStudents
   * const userStudent = await prisma.userStudent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserStudentCreateManyArgs>(args?: Prisma.SelectSubset<T, UserStudentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserStudents and returns the data saved in the database.
   * @param {UserStudentCreateManyAndReturnArgs} args - Arguments to create many UserStudents.
   * @example
   * // Create many UserStudents
   * const userStudent = await prisma.userStudent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserStudents and only return the `id`
   * const userStudentWithIdOnly = await prisma.userStudent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserStudentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserStudentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserStudent.
   * @param {UserStudentDeleteArgs} args - Arguments to delete one UserStudent.
   * @example
   * // Delete one UserStudent
   * const UserStudent = await prisma.userStudent.delete({
   *   where: {
   *     // ... filter to delete one UserStudent
   *   }
   * })
   * 
   */
  delete<T extends UserStudentDeleteArgs>(args: Prisma.SelectSubset<T, UserStudentDeleteArgs<ExtArgs>>): Prisma.Prisma__UserStudentClient<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserStudent.
   * @param {UserStudentUpdateArgs} args - Arguments to update one UserStudent.
   * @example
   * // Update one UserStudent
   * const userStudent = await prisma.userStudent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserStudentUpdateArgs>(args: Prisma.SelectSubset<T, UserStudentUpdateArgs<ExtArgs>>): Prisma.Prisma__UserStudentClient<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserStudents.
   * @param {UserStudentDeleteManyArgs} args - Arguments to filter UserStudents to delete.
   * @example
   * // Delete a few UserStudents
   * const { count } = await prisma.userStudent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserStudentDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserStudentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserStudents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStudentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserStudents
   * const userStudent = await prisma.userStudent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserStudentUpdateManyArgs>(args: Prisma.SelectSubset<T, UserStudentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserStudents and returns the data updated in the database.
   * @param {UserStudentUpdateManyAndReturnArgs} args - Arguments to update many UserStudents.
   * @example
   * // Update many UserStudents
   * const userStudent = await prisma.userStudent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserStudents and only return the `id`
   * const userStudentWithIdOnly = await prisma.userStudent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserStudentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserStudentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserStudent.
   * @param {UserStudentUpsertArgs} args - Arguments to update or create a UserStudent.
   * @example
   * // Update or create a UserStudent
   * const userStudent = await prisma.userStudent.upsert({
   *   create: {
   *     // ... data to create a UserStudent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserStudent we want to update
   *   }
   * })
   */
  upsert<T extends UserStudentUpsertArgs>(args: Prisma.SelectSubset<T, UserStudentUpsertArgs<ExtArgs>>): Prisma.Prisma__UserStudentClient<runtime.Types.Result.GetResult<Prisma.$UserStudentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserStudents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStudentCountArgs} args - Arguments to filter UserStudents to count.
   * @example
   * // Count the number of UserStudents
   * const count = await prisma.userStudent.count({
   *   where: {
   *     // ... the filter for the UserStudents we want to count
   *   }
   * })
  **/
  count<T extends UserStudentCountArgs>(
    args?: Prisma.Subset<T, UserStudentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserStudentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserStudent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStudentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserStudentAggregateArgs>(args: Prisma.Subset<T, UserStudentAggregateArgs>): Prisma.PrismaPromise<GetUserStudentAggregateType<T>>

  /**
   * Group by UserStudent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserStudentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserStudentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserStudentGroupByArgs['orderBy'] }
      : { orderBy?: UserStudentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserStudentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserStudentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserStudent model
 */
readonly fields: UserStudentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserStudent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserStudentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  student<T extends Prisma.StudentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentDefaultArgs<ExtArgs>>): Prisma.Prisma__StudentClient<runtime.Types.Result.GetResult<Prisma.$StudentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  group<T extends Prisma.GroupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GroupDefaultArgs<ExtArgs>>): Prisma.Prisma__GroupClient<runtime.Types.Result.GetResult<Prisma.$GroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserStudent model
 */
export interface UserStudentFieldRefs {
  readonly id: Prisma.FieldRef<"UserStudent", 'String'>
  readonly userId: Prisma.FieldRef<"UserStudent", 'String'>
  readonly studentId: Prisma.FieldRef<"UserStudent", 'String'>
  readonly groupId: Prisma.FieldRef<"UserStudent", 'String'>
  readonly relation: Prisma.FieldRef<"UserStudent", 'String'>
}
    

// Custom InputTypes
/**
 * UserStudent findUnique
 */
export type UserStudentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
  /**
   * Filter, which UserStudent to fetch.
   */
  where: Prisma.UserStudentWhereUniqueInput
}

/**
 * UserStudent findUniqueOrThrow
 */
export type UserStudentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
  /**
   * Filter, which UserStudent to fetch.
   */
  where: Prisma.UserStudentWhereUniqueInput
}

/**
 * UserStudent findFirst
 */
export type UserStudentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
  /**
   * Filter, which UserStudent to fetch.
   */
  where?: Prisma.UserStudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserStudents to fetch.
   */
  orderBy?: Prisma.UserStudentOrderByWithRelationInput | Prisma.UserStudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserStudents.
   */
  cursor?: Prisma.UserStudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserStudents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserStudents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserStudents.
   */
  distinct?: Prisma.UserStudentScalarFieldEnum | Prisma.UserStudentScalarFieldEnum[]
}

/**
 * UserStudent findFirstOrThrow
 */
export type UserStudentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
  /**
   * Filter, which UserStudent to fetch.
   */
  where?: Prisma.UserStudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserStudents to fetch.
   */
  orderBy?: Prisma.UserStudentOrderByWithRelationInput | Prisma.UserStudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserStudents.
   */
  cursor?: Prisma.UserStudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserStudents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserStudents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserStudents.
   */
  distinct?: Prisma.UserStudentScalarFieldEnum | Prisma.UserStudentScalarFieldEnum[]
}

/**
 * UserStudent findMany
 */
export type UserStudentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
  /**
   * Filter, which UserStudents to fetch.
   */
  where?: Prisma.UserStudentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserStudents to fetch.
   */
  orderBy?: Prisma.UserStudentOrderByWithRelationInput | Prisma.UserStudentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserStudents.
   */
  cursor?: Prisma.UserStudentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserStudents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserStudents.
   */
  skip?: number
  distinct?: Prisma.UserStudentScalarFieldEnum | Prisma.UserStudentScalarFieldEnum[]
}

/**
 * UserStudent create
 */
export type UserStudentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
  /**
   * The data needed to create a UserStudent.
   */
  data: Prisma.XOR<Prisma.UserStudentCreateInput, Prisma.UserStudentUncheckedCreateInput>
}

/**
 * UserStudent createMany
 */
export type UserStudentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserStudents.
   */
  data: Prisma.UserStudentCreateManyInput | Prisma.UserStudentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserStudent createManyAndReturn
 */
export type UserStudentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * The data used to create many UserStudents.
   */
  data: Prisma.UserStudentCreateManyInput | Prisma.UserStudentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserStudent update
 */
export type UserStudentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
  /**
   * The data needed to update a UserStudent.
   */
  data: Prisma.XOR<Prisma.UserStudentUpdateInput, Prisma.UserStudentUncheckedUpdateInput>
  /**
   * Choose, which UserStudent to update.
   */
  where: Prisma.UserStudentWhereUniqueInput
}

/**
 * UserStudent updateMany
 */
export type UserStudentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserStudents.
   */
  data: Prisma.XOR<Prisma.UserStudentUpdateManyMutationInput, Prisma.UserStudentUncheckedUpdateManyInput>
  /**
   * Filter which UserStudents to update
   */
  where?: Prisma.UserStudentWhereInput
  /**
   * Limit how many UserStudents to update.
   */
  limit?: number
}

/**
 * UserStudent updateManyAndReturn
 */
export type UserStudentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * The data used to update UserStudents.
   */
  data: Prisma.XOR<Prisma.UserStudentUpdateManyMutationInput, Prisma.UserStudentUncheckedUpdateManyInput>
  /**
   * Filter which UserStudents to update
   */
  where?: Prisma.UserStudentWhereInput
  /**
   * Limit how many UserStudents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserStudent upsert
 */
export type UserStudentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
  /**
   * The filter to search for the UserStudent to update in case it exists.
   */
  where: Prisma.UserStudentWhereUniqueInput
  /**
   * In case the UserStudent found by the `where` argument doesn't exist, create a new UserStudent with this data.
   */
  create: Prisma.XOR<Prisma.UserStudentCreateInput, Prisma.UserStudentUncheckedCreateInput>
  /**
   * In case the UserStudent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserStudentUpdateInput, Prisma.UserStudentUncheckedUpdateInput>
}

/**
 * UserStudent delete
 */
export type UserStudentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
  /**
   * Filter which UserStudent to delete.
   */
  where: Prisma.UserStudentWhereUniqueInput
}

/**
 * UserStudent deleteMany
 */
export type UserStudentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserStudents to delete
   */
  where?: Prisma.UserStudentWhereInput
  /**
   * Limit how many UserStudents to delete.
   */
  limit?: number
}

/**
 * UserStudent without action
 */
export type UserStudentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserStudent
   */
  select?: Prisma.UserStudentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserStudent
   */
  omit?: Prisma.UserStudentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserStudentInclude<ExtArgs> | null
}
