
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
const __dirname = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Suggestions
 * const suggestions = await prisma.suggestion.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<ClientOptions extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions, Log = $Class.LogOptions<ClientOptions>, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<ClientOptions, Log, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-darwin-arm64.dylib.node")
path.join(process.cwd(), "src/_generated/prisma/libquery_engine-darwin-arm64.dylib.node")

// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-linux-musl-openssl-3.0.x.so.node")
path.join(process.cwd(), "src/_generated/prisma/libquery_engine-linux-musl-openssl-3.0.x.so.node")

// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node")
path.join(process.cwd(), "src/_generated/prisma/libquery_engine-linux-musl-arm64-openssl-3.0.x.so.node")

/**
 * Model Suggestion
 * 
 */
export type Suggestion = Prisma.SuggestionModel
/**
 * Model SuggestionComment
 * 
 */
export type SuggestionComment = Prisma.SuggestionCommentModel
/**
 * Model SuggestionVote
 * 
 */
export type SuggestionVote = Prisma.SuggestionVoteModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model UserGroup
 * 
 */
export type UserGroup = Prisma.UserGroupModel
/**
 * Model UserStudent
 * 
 */
export type UserStudent = Prisma.UserStudentModel
/**
 * Model Student
 * 
 */
export type Student = Prisma.StudentModel
/**
 * Model Group
 * 
 */
export type Group = Prisma.GroupModel
/**
 * Model Organization
 * 
 */
export type Organization = Prisma.OrganizationModel
/**
 * Model OrganizationMembership
 * 
 */
export type OrganizationMembership = Prisma.OrganizationMembershipModel

export type SuggestionStatus = $Enums.SuggestionStatus
export const SuggestionStatus = $Enums.SuggestionStatus

export type SuggestionVoteType = $Enums.SuggestionVoteType
export const SuggestionVoteType = $Enums.SuggestionVoteType

export type RoleName = $Enums.RoleName
export const RoleName = $Enums.RoleName

export type UserStatus = $Enums.UserStatus
export const UserStatus = $Enums.UserStatus
