
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/
export const SuggestionStatus = {
  DISCUSSION: 'DISCUSSION',
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETE: 'COMPLETE'
} as const

export type SuggestionStatus = (typeof SuggestionStatus)[keyof typeof SuggestionStatus]


export const SuggestionVoteType = {
  LIKE: 'LIKE',
  DISLIKE: 'DISLIKE'
} as const

export type SuggestionVoteType = (typeof SuggestionVoteType)[keyof typeof SuggestionVoteType]


export const RoleName = {
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
  USER: 'USER'
} as const

export type RoleName = (typeof RoleName)[keyof typeof RoleName]


export const UserStatus = {
  INVITED: 'INVITED',
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]
