
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Suggestion.js'
export type * from './models/SuggestionComment.js'
export type * from './models/SuggestionVote.js'
export type * from './models/Role.js'
export type * from './models/User.js'
export type * from './models/UserGroup.js'
export type * from './models/UserStudent.js'
export type * from './models/Student.js'
export type * from './models/Group.js'
export type * from './models/Organization.js'
export type * from './models/OrganizationMembership.js'
export type * from './commonInputTypes.js'