name: CD

on:
  push:
    branches:
      # - stage
      # - main
      - gcp

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'stage' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying branch: ${{ github.ref_name }}"
          echo "To environment: ${{ github.ref_name == 'main' && 'production' || 'stage' }}"

      - name: Read Node.js Version
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Create .env file
        run: |
          cat <<EOF > ./packages/app/.env.local
          VITE_CLERK_PUBLISHABLE_KEY=${{ vars.VITE_CLERK_PUBLISHABLE_KEY }}
          EOF

      # - name: DEBUG
      #   run: |
      #     echo "VITE_CLERK_PUBLISHABLE_KEY=${{ vars.VITE_CLERK_PUBLISHABLE_KEY }}"
      #     cat ./packages/app/.env.local

      - name: Enable Corepack # Ensures the correct version of yarn is used
        run: corepack enable

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build Project
        run: yarn build
        env:
          VITE_CLERK_PUBLISHABLE_KEY: ${{ vars.VITE_CLERK_PUBLISHABLE_KEY }}
          TURBO_TOKEN: ${{secrets.TURBO_TOKEN}}
          TURBO_TEAM: ${{secrets.TURBO_TEAM_ID}}

      - name: --- DEBUG BUILD FILE ---
        run: |
          FILE=$(ls ./packages/app/build/server/assets/server-build-* | head -n 1)
          echo "Showing contents of $FILE"
          cat "$FILE"

      - name: GCP - Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: GCP - Setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: GCP - Build using Cloud Build
        run: |
          echo "Building ${{vars.SERVICE_NAME}}"
          gcloud builds submit . \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{vars.SERVICE_NAME}} \

      - name: GCP - Deploy to Cloud Run
        run: |
          echo "Deploying ${{vars.SERVICE_NAME}} to Google Cloud Run"
          gcloud run deploy ${{vars.SERVICE_NAME}} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{vars.SERVICE_NAME}} \
            --platform managed \
            --region us-central1 \
            --set-env-vars NODE_ENV=production,\
          NCCL_APP_URL=${{ secrets.NCCL_APP_URL }},\
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }},\
          GOOGLE_CALENDAR_API_KEY=${{ secrets.GOOGLE_CALENDAR_API_KEY }},\
          GOOGLE_CALENDAR_ID_NCCL_PUBLIC=${{ secrets.GOOGLE_CALENDAR_ID_NCCL_PUBLIC }}
