name: CD

# on:
#   push:
#     branches:
#       - dev

on:
  pull_request:
    branches:
      - dev

env:
  # CI
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM_ID: ${{ secrets.TURBO_TEAM_ID }}
  # CD
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  GCP_CLOUDRUN_SERVICE_APP: ${{ vars.GCP_CLOUDRUN_SERVICE_APP }}
  GCP_CLOUDRUN_SERVICE_API: ${{ vars.GCP_CLOUDRUN_SERVICE_API }}
  GCP_ARTIFACT_REGISTRY_APP: ${{ vars.GCP_ARTIFACT_REGISTRY_APP }}
  GCP_ARTIFACT_REGISTRY_API: ${{ vars.GCP_ARTIFACT_REGISTRY_API }}
  # Runtime
  NODE_ENV: production
  NCCL_ENVIRONMENT: ${{ vars.NCCL_ENVIRONMENT }}
  NCCL_APP_URL: ${{ vars.NCCL_APP_URL }}
  NCCL_API_URL: ${{ vars.NCCL_API_URL }}
  GCP_CLOUD_STORAGE_BUCKET: ${{ vars.GCP_CLOUD_STORAGE_BUCKET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{ vars.SENTRY_ORG }}
  SENTRY_PROJECT_APP: ${{ vars.SENTRY_PROJECT_APP }}
  SENTRY_PROJECT_API: ${{ vars.SENTRY_PROJECT_API }}
  SENTRY_DSN_APP: ${{ vars.SENTRY_DSN_APP }}
  SENTRY_DSN_API: ${{ vars.SENTRY_DSN_API }}
  SENTRY_ENABLED: ${{ vars.SENTRY_ENABLED }}
  # Seed
  SUPER_USER_PASSWORD: ${{ secrets.SUPER_USER_PASSWORD }}
  SUPER_USER_EMAIL: ${{ secrets.SUPER_USER_EMAIL }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'dev' }}
    outputs:
      api_image_name: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_API }}/${{ vars.GCP_CLOUDRUN_SERVICE_API }}
      app_image_name: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_ARTIFACT_REGISTRY_APP }}/${{ vars.GCP_CLOUDRUN_SERVICE_APP }}
      comparison_branch: ${{ github.ref_name == 'main' && 'main' || 'dev' }}
      environment: ${{ github.ref_name == 'main' && 'production' || 'dev' }}
      # node_version: ${{ steps.db.outputs.node_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Set Up node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build monorepo
        run: yarn build

      - name: Validate environment
        run: node scripts/validate.cd.js

      - name: Install production dependencies
        run: yarn workspaces focus --production --all

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: monorepo-build
          path: .

  db_check:
    name: Check DB
    runs-on: ubuntu-latest
    needs: [setup]
    outputs:
      should_migrate: ${{ steps.db.outputs.should_migrate }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch comparison branch
        run: git fetch origin ${{ needs.setup.outputs.comparison_branch }}

      - id: db
        name: Check if Prisma Migrations Have Changed
        working-directory: packages/api
        run: |
          echo "🔍 Checking for changes to 'prisma/migrations/' between this commit and origin/${{ needs.setup.outputs.comparison_branch }}"
          CHANGED_FILES=$(git diff --name-only origin/${{ needs.setup.outputs.comparison_branch }}...HEAD)
          echo

          echo "📄 Files changed in commit range:"
          echo "$CHANGED_FILES"
          echo

          if printf '%s\n' "$CHANGED_FILES" | grep -q '^packages/api/prisma/migrations/'; then
            echo "✅ Detected changes in 'prisma/migrations/' — running DB migration."
            echo "should_migrate=true" >> $GITHUB_OUTPUT
          else
            echo "ℹ️ No changes to 'prisma/migrations/' — skipping DB migration."
            echo "should_migrate=false" >> $GITHUB_OUTPUT
          fi

  db_migrate:
    name: Migrate DB
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'dev' }}
    needs: [setup, db_check]
    if: needs.db_check.outputs.should_migrate == 'true'
    outputs:
      ran: "true"

    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: monorepo-build

      - name: Enable corepack
        run: corepack enable

      - name: Set Up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Migrate DB
        working-directory: packages/api
        run: npx prisma migrate deploy

      - name: Seed DB
        working-directory: packages/api
        run: npx prisma db seed

  build_api_image:
    name: Build API Image
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.setup.outputs.environment }}
    needs: [setup]
    if: always() && needs.setup.result == 'success'
    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: monorepo-build

      - name: Authenticate GCP
        id: google_auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          token_format: access_token
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build image and push to GAR
        run: |
          docker build . -f packages/api/Dockerfile -t ${{ needs.setup.outputs.api_image_name }} 
          echo "${{ steps.google_auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ vars.GCP_REGION }}-docker.pkg.dev
          docker push ${{ needs.setup.outputs.api_image_name }}

  build_app_image:
    name: Build App
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.setup.outputs.environment }}
    needs: [setup]
    if: always() && needs.setup.result == 'success'
    steps:
      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: monorepo-build

      - name: Authenticate GCP
        id: google_auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          token_format: access_token
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build image and push to GAR
        run: |
          docker build . -f packages/app/Dockerfile -t ${{ needs.setup.outputs.app_image_name }}
          echo "${{ steps.google_auth.outputs.access_token }}" | docker login -u oauth2accesstoken --password-stdin https://${{ vars.GCP_REGION }}-docker.pkg.dev
          docker push ${{ needs.setup.outputs.app_image_name }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [setup, build_api_image, build_app_image, db_check, db_migrate]
    if: always() && needs.build_api_image.result == 'success' && needs.build_app_image.result == 'success' && needs.db_check.result == 'success' && (needs.db_migrate.result == 'success' || needs.db_migrate.result == 'skipped')
    environment:
      name: ${{ needs.setup.outputs.environment }}
    steps:
      - name: Authenticate GCP
        id: google_auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          token_format: access_token
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy [API] to Cloudrun
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service: ${{ vars.GCP_CLOUDRUN_SERVICE_API }}
          image: ${{ needs.setup.outputs.api_image_name }}
          region: ${{ vars.GCP_REGION }}
          env_vars: |-
            NCCL_ENVIRONMENT=${{ vars.NCCL_ENVIRONMENT }}
            NCCL_APP_URL=${{ vars.NCCL_APP_URL }}
            NCCL_API_URL=${{ vars.NCCL_API_URL }}
            GCP_CLOUD_STORAGE_BUCKET=${{ vars.GCP_CLOUD_STORAGE_BUCKET }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            SENTRY_ORG=${{ vars.SENTRY_ORG }}
            SENTRY_PROJECT_API=${{ vars.SENTRY_PROJECT_API }}
            SENTRY_DSN_API=${{ vars.SENTRY_DSN_API }}
            SENTRY_ENABLED=${{ vars.SENTRY_ENABLED }}

      - name: Deploy [App] to Cloudrun
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          service: ${{ vars.GCP_CLOUDRUN_SERVICE_APP }}
          image: ${{ needs.setup.outputs.app_image_name }}
          region: ${{ vars.GCP_REGION }}
          env_vars: |-
            NCCL_ENVIRONMENT=${{ vars.NCCL_ENVIRONMENT }}
            NCCL_APP_URL=${{ vars.NCCL_APP_URL }}
            NCCL_API_URL=${{ vars.NCCL_API_URL }}
            GCP_CLOUD_STORAGE_BUCKET=${{ vars.GCP_CLOUD_STORAGE_BUCKET }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            SENTRY_ORG=${{ vars.SENTRY_ORG }}
            SENTRY_PROJECT_APP=${{ vars.SENTRY_PROJECT_APP }}
            SENTRY_DSN_APP=${{ vars.SENTRY_DSN_APP }}
            SENTRY_ENABLED=${{ vars.SENTRY_ENABLED }}
