name: CI - Build & Test

on:
  pull_request:
    branches:
      # - dev
      - N_A

jobs:
  ci:
    name: CI - Build & test
    runs-on: ubuntu-latest
    environment:
      name: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create the base env file for the build
      - name: Create .env file
        run: |
          touch .env
          echo NODE_ENV=production >> .env
          echo NCCL_ENVIRONMENT=${{ vars.NCCL_ENVIRONMENT }} >> .env
          echo NCCL_APP_URL=${{ vars.NCCL_APP_URL }} >> .env
          echo NCCL_API_URL=${{ vars.NCCL_API_URL }} >> .env
          echo GCP_CLOUD_STORAGE_BUCKET=${{ secrets.GCP_CLOUD_STORAGE_BUCKET }} >> .env
          echo BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }} >> .env
          echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
          echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
          echo SUPER_USER_EMAIL=${{ secrets.SUPER_USER_EMAIL }} >> .env
          echo SUPER_USER_PASSWORD=${{ secrets.SUPER_USER_PASSWORD }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env

      - name: Enable corepack
        run: corepack enable

      - name: Set Up node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
        env:
          TURBO_TOKEN: ${{secrets.TURBO_TOKEN}}
          TURBO_TEAM: ${{secrets.TURBO_TEAM_ID}}

      - name: Install production dependencies
        shell: bash
        run: yarn workspaces focus --production --all

      # Part of the setup script is to read values off
      # of the base env file to create a new .env.spec
      # to be able to create the test environment
      - name: Setup e2e environment
        run: yarn e2e:up

      - name: Run API tests
        run: yarn playwright test
