name: CI - Build & Test

on:
  pull_request:
    branches:
      - dev

jobs:
  ci:
    name: CI - Build & test
    runs-on: ubuntu-latest
    environment:
      name: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo TURBO_TOKEN=${{ secrets.TURBO_TOKEN }} >> .env
          echo TURBO_TEAM_ID=${{ secrets.TURBO_TEAM_ID }} >> .env
          echo NODE_ENV=production >> .env
          echo NCCL_ENVIRONMENT=${{ vars.NCCL_ENVIRONMENT }} >> .env
          echo NCCL_APP_URL=${{ vars.NCCL_APP_URL }} >> .env
          echo NCCL_API_URL=${{ vars.NCCL_API_URL }} >> .env
          echo GCP_CLOUD_STORAGE_BUCKET=${{ secrets.GCP_CLOUD_STORAGE_BUCKET }} >> .env
          echo BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }} >> .env
          echo GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} >> .env
          echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
          echo SUPER_USER_PASSWORD=${{ secrets.SUPER_USER_PASSWORD }} >> .env
          echo SUPER_USER_EMAIL=${{ secrets.SUPER_USER_EMAIL }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env

      # Validates that all of necessary env vars have been loaded into the environment
      - name: Validate
        run: yarn validate:ci

      - name: Build
        uses: ./.github/actions/setup-and-install

      - name: Start containers
        run: docker compose -f=docker-compose.spec.yml --progress plain up -d

      - name: Pause for containers
        run: |
          docker compose wait

      - name: Reset and seed DB
        working-directory: packages/api
        run: docker compose -f=docker-compose.spec.yml exec -T api yarn prisma migrate reset --force --skip-generate

      - name: Run API tests
        run: yarn playwright test
